Replace log_error with specific debug functions

diff --git a/common.sh.in b/common.sh.in
--- a/common.sh.in
+++ b/common.sh.in
@@ -53,8 +53,6 @@ die() { printerr "$@"; exit 1; }
 
 croak() { usage >&2; die "$@"; }
 
-log_error() { printf '%s\n' "$*" >&2; }
-
 cleanup() {
     if test ${#CLEANUP[*]} -gt 0; then
         LAST_ELEMENT=`expr ${#CLEANUP[*]} - 1 || :`
@@ -74,7 +72,7 @@ pop_cleanup() {
 }
 
 get_os_type() {
-    test -n "$TARGET" || { log_error 'TARGET is not set in get_os_type'; exit 1; }
+    test -n "$TARGET" || die 'TARGET is not set in get_os_type\n'
     if test -e "${TARGET}/etc/redhat-release"; then
         OS_TYPE='redhat'
     elif test -e "${TARGET}/etc/debian_version"; then
@@ -87,7 +85,7 @@ get_os_type() {
 }
 
 get_os() {
-    test -n "$TARGET" || { log_error 'TARGET is not set in get_os'; exit 1; }
+    test -n "$TARGET" || die 'TARGET is not set in get_os\n'
     _lsb='/usr/bin/lsb_release'
     if test -e "${TARGET}/$_lsb"; then
         OPERATING_SYSTEM="$(chroot "$TARGET" "$_lsb" -i -s | tr '[:upper:]' '[:lower:]')"
@@ -107,7 +105,7 @@ get_os() {
 }
 
 get_os_release() {
-    test -n "$TARGET" || { log_error 'TARGET is not set in get_os_release'; exit 1; }
+    test -n "$TARGET" || die 'TARGET is not set in get_os_release\n'
     _lsb='/usr/bin/lsb_release'
     if test -e "${TARGET}/$_lsb"; then
         OS_RELEASE="$(chroot "$TARGET" "$_lsb" -r -s | tr '[:upper:]' '[:lower:]')"
@@ -243,11 +241,11 @@ map_disk0() {
             grep -m 1 -- "-1.*$BLOCKDEV" | \
             "$AWK" '{print $1}'
     `"
-    test -n "$_filesystem_dev1_base" || { log_error 'Cannot interpret kpartx output and get partition mapping'; exit 1; }
+    test -n "$_filesystem_dev1_base" || die 'Cannot interpret kpartx output and get partition mapping\n'
     $KPARTX -a -p- "$BLOCKDEV" >/dev/null
     _filesystem_dev="/dev/mapper/${_filesystem_dev1_base%-1}"
     test -b "/dev/mapper/$_filesystem_dev1_base" || \
-        { log_error "Can't find kpartx mapped partition: /dev/mapper/$_filesystem_dev1_base"; exit 1; }
+        die 'Can'\''t find kpartx mapped partition: /dev/mapper/%s\n' "$_filesystem_dev1_base"
     printf '%s' "$_filesystem_dev"
 }
 
@@ -329,7 +327,7 @@ get_service_manager() {
 }
 
 setup_console() {
-    test -n "$TARGET" || { log_error 'TARGET not set for setup_console'; exit 1; }
+    test -n "$TARGET" || die 'TARGET not set for setup_console\n'
     case "`get_service_manager`" in
         upstart)
             if test -e "${TARGET}/etc/event.d/tty1"; then
@@ -360,7 +358,7 @@ setup_console() {
                     sed --follow-symlinks -i -e 's/.*T0.*/T0:23:respawn:\/sbin\/getty -L ttyS0 115200 vt100/' "${TARGET}/etc/inittab"
                     ;;
                 *)
-                    log_error 'No support for your OS in instance-image, skipping...'
+                    verbprint 'No support for your OS in instance-image, skipping...\n'
                     ;;
             esac
             ;;
@@ -371,13 +369,13 @@ setup_console() {
 }
 
 filesystem_check() {
-    test -n "$TARGET" || { log_error 'TARGET not set for filesystem_check'; exit 1; }
+    test -n "$TARGET" || die 'TARGET not set for filesystem_check\n'
     get_os
     case "$OPERATING_SYSTEM" in
         fedora|centos|redhat)
             # we have to force a filesystem relabeling for SELinux after messing
             # around with the filesystem in fedora
-            log_error 'Enforce an automatic relabeling in the initial boot process...'
+            verbprint 'Enforce an automatic relabeling in the initial boot process...\n'
             touch "${TARGET}/.autorelabel"
             ;;
     esac
@@ -385,16 +383,16 @@ filesystem_check() {
 
 get_api10_arguments() {
     test -n "$INSTANCE_NAME" && test -n "$HYPERVISOR" && test -n "$DISK_COUNT" || \
-        { log_error 'Missing OS API Variable:'; log_error '(INSTANCE_NAME, HYPERVISOR or DISK_COUNT)'; exit 1; }
+        die 'Missing OS API Variable:\n(INSTANCE_NAME, HYPERVISOR or DISK_COUNT)\n'
     instance="$INSTANCE_NAME"
-    test 1 -le $DISK_COUNT && test -n "$DISK_0_PATH" || { log_error 'At least one disk is needed'; exit 1; }
+    test 1 -le $DISK_COUNT && test -n "$DISK_0_PATH" || die 'At least one disk is needed\n'
     case "$SCRIPT_NAME" in
         export)
-            test -n "$EXPORT_DEVICE" || log_error 'Missing OS API Variable EXPORT_DEVICE'
+            test -n "$EXPORT_DEVICE" || die 'Missing OS API Variable EXPORT_DEVICE\n'
             BLOCKDEV="$EXPORT_DEVICE"
             ;;
         import)
-            test -n "$IMPORT_DEVICE" || log_error 'Missing OS API Variable IMPORT_DEVICE'
+            test -n "$IMPORT_DEVICE" || die 'Missing OS API Variable IMPORT_DEVICE\n'
             BLOCKDEV="$IMPORT_DEVICE"
             ;;
         *)
@@ -402,13 +400,13 @@ get_api10_arguments() {
             ;;
     esac
     ! test 'rename' = "$SCRIPT_NAME" || test -n "$OLD_INSTANCE_NAME" || \
-         { log_error 'Missing OS API Variable OLD_INSTANCE_NAME'; exit 1; }
+        die 'Missing OS API Variable OLD_INSTANCE_NAME\n'
     old_name="$OLD_INSTANCE_NAME"
 }
 
 get_api20_parameters() {
     test -n "$OSP_IMG_ID" && test -n "$OSP_IMG_FORMAT" || \
-        { log_error 'Missing OS API Parameter:'; log_error '(OSP_IMG_ID or OSP_IMG_FORMAT)'; exit 1; }
+        die 'Missing OS API Parameter:\n(OSP_IMG_ID or OSP_IMG_FORMAT)\n'
     IMG_ID="$OSP_IMG_ID"
     IMAGE_TYPE="$OSP_IMG_FORMAT"
     IMG_SSH_KEY_URL="$OSP_IMG_SSH_KEY_URL"
@@ -463,21 +461,20 @@ get_api20_parameters
 IMAGE_NAME="$IMG_ID"
 
 if test -n "$OS_VARIANT"; then
-    test -d "$VARIANTS_DIR" || { log_error "OS Variants directory $VARIANTS_DIR doesn't exist"; exit 1; }
+    test -d "$VARIANTS_DIR" || die 'OS Variants directory %s doesn'\''t exist\n' "$VARIANTS_DIR"
     VARIANT_CONFIG="${VARIANTS_DIR}/${OS_VARIANT}.conf"
     if test -f "$VARIANT_CONFIG"; then
         . "$VARIANT_CONFIG"
     else
         if grep -qxF "$OS_VARIANT" variants.list; then
-            log_error 'ERROR: instance-image configuration error'
-            log_error "  Published variant $OS_VARIANT is missing its config file"
-            log_error "  Please create $VARIANT_CONFIG or unpublish the variant"
-            log_error "  (by removing $OS_VARIANT from variants.list)"
+            die 'ERROR: instance-image configuration error
+  Published variant %s is missing its config file
+  Please create %s or unpublish the variant
+  (by removing %s from variants.list)\n' "$OS_VARIANT" "$VARIANT_CONFIG" "$OS_VARIANT"
         else
-            log_error "Unofficial variant $OS_VARIANT is unsupported"
-            log_error 'Most probably this is a user error, forcing a wrong name'
-            log_error "To support this variant please create file $VARIANT_CONFIG"
+            die 'Unofficial variant %s is unsupported
+Most probably this is a user error, forcing a wrong name
+To support this variant please create file %s\n' "$OS_VARIANT" "$VARIANT_CONFIG"
         fi
-        exit 1
     fi
 fi
diff --git a/create b/create
--- a/create
+++ b/create
@@ -38,13 +38,13 @@ if ! test -z "$IMAGE_URL"; then
     cd "$CACHE_DIR"
     if ! test -e "${CACHE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT"; then
         $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}$IMG_EXT" >/dev/null 2>/dev/null || \
-            { log_error "Failed to find the image on $IMAGE_URL"; exit 1; }
+            die 'Failed to find the image on %s\n' "$IMAGE_URL"
     fi
     if test 'yes' = "$IMG_VERIFY"; then
         $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null 2>/dev/null || \
-            { log_error 'Failed to find the checksum file'; exit 1; }
+            die 'Failed to find the checksum file\n'
         "$SHA1SUM" -c "${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null || \
-            { log_error 'Image doesn'\''t match checksum!'; exit 1; }
+            die 'Image doesn'\''t match checksum!\n'
     fi
     ! test 'yes' = "$IMG_CLEANUP" || \
         CLEANUP+=("rm -f \"${CACHE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT\" \"${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig\"")
@@ -73,12 +73,12 @@ if test 'no' = "$CDINSTALL"; then
     DISK_SIZE="$(expr `"$BLOCKDEV_CMD" --getsize64 "$BLOCKDEV"` / 1048576)"
 
     if test 'yes' = "$SWAP"; then
-        test -n "$SWAP_SIZE" || { log_error 'SWAP_SIZE not set however SWAP is enabled'; exit 1; }
+        test -n "$SWAP_SIZE" || die 'SWAP_SIZE not set however SWAP is enabled\n'
         test $SWAP_SIZE -le $DISK_SIZE || \
-            { log_error 'SWAP_SIZE larger than system disk size: '; log_error "  ${SWAP_SIZE}MB swap > ${DISK_SIZE}MB system disk"; exit 1; }
+            die 'SWAP_SIZE larger than system disk size:\n  %sMB swap > %sMB system disk\n' "$SWAP_SIZE" "$DISK_SIZE"
     fi
 
-    test -f "$IMAGE_FILE" || { log_error "Can't find image file: $IMAGE_FILE"; exit 1; }
+    test -f "$IMAGE_FILE" || die 'Can'\''t find image file: %s\n' "$IMAGE_FILE"
 
     # If the image is tarball based, then we need to manually create the
     # volumes, filesystems, etc
@@ -129,7 +129,7 @@ if test 'no' = "$CDINSTALL"; then
             ( cd "$TARGET"; restore -r -y -f "$root_dump" >/dev/null )
             if test -n "$boot_dev"; then
                 boot_dump="${IMAGE_FILE%root.dump}boot.dump"
-                test -f "$boot_dump" || { log_error "Can't find image file: $boot_dump"; exit 1; }
+                test -f "$boot_dump" || die 'Can'\''t find image file: %s\n' "$boot_dump"
                 ( cd "${TARGET}/boot"; restore -r -y -f "$boot_dump" >/dev/null )
             fi
             ;;
diff --git a/example/hooks/grub b/example/hooks/grub
--- a/example/hooks/grub
+++ b/example/hooks/grub
@@ -26,7 +26,7 @@ set -e
 . ./common.sh
 debug set -x
 
-test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
+test -d "$TARGET" || die 'Missing target directory\n'
 
 # Set disk based on type of hypervisor
 if test 'kvm' = "$HYPERVISOR"; then
@@ -153,7 +153,7 @@ if test 'True' = "$INSTANCE_HV_serial_console"; then
         printf 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"\n' \
             >>"${TARGET}/etc/default/grub"
     else
-        log_error 'No grub bootloader found, skipping...'
+        verbprint 'No grub bootloader found, skipping...\n'
     fi
 fi
 
diff --git a/example/hooks/interfaces b/example/hooks/interfaces
--- a/example/hooks/interfaces
+++ b/example/hooks/interfaces
@@ -28,14 +28,14 @@ FQDN="$INSTANCE_NAME"
 SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
 STATIC=''
 
-test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
+test -d "$TARGET" || die 'Missing target directory\n'
 
-test -n "$NIC_COUNT" || { log_error 'Missing NIC_COUNT'; exit 1; }
+test -n "$NIC_COUNT" || die 'Missing NIC_COUNT\n'
 
 if test -f "${NETWORKS_DIR}/instances/$FQDN'; then
     STATIC='yes'
     . "${NETWORKS_DIR}/instances/$FQDN"
-    test -f "${NETWORKS_DIR}/subnets/$SUBNET" || { log_error "No subnet file for subnet ${SUBNET}!"; exit 1; }
+    test -f "${NETWORKS_DIR}/subnets/$SUBNET" || die 'No subnet file for subnet %s!\n' "$SUBNET"
     . "${NETWORKS_DIR}/subnets/$SUBNET"
 fi
 
@@ -78,7 +78,7 @@ EOF
 }
 
 debian_setup() {
-    test -d "${TARGET}/etc/network" || { log_error 'Missing target network directory'; exit 1; }
+    test -d "${TARGET}/etc/network" || die 'Missing target network directory\n'
 
     if test -z "$STATIC"; then
         cat >"${TARGET}/etc/network/interfaces" <<EOF
@@ -126,7 +126,7 @@ EOF
 }
 
 redhat_setup() {
-    test -d "${TARGET}/etc/sysconfig/network-scripts" || { log_error 'Missing target network directory'; exit 1; }
+    test -d "${TARGET}/etc/sysconfig/network-scripts" || die 'Missing target network directory\n'
     if test -z "$STATIC"; then
         cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
 DEVICE=eth0
@@ -161,7 +161,7 @@ EOF
 }
 
 gentoo_setup() {
-    test -f "${TARGET}/etc/conf.d/net" || { log_error 'Missing target network file'; exit 1; }
+    test -f "${TARGET}/etc/conf.d/net" || die 'Missing target network file\n'
     if test -z "$STATIC"; then
         cat >"${TARGET}/etc/conf.d/net" <<EOF
 config_eth0=( 'dhcp' )
@@ -193,7 +193,7 @@ EOF
 }
 
 suse_setup() {
-    test -d "${TARGET}/etc/sysconfig/network" || { log_error 'Missing target network directory'; exit 1; }
+    test -d "${TARGET}/etc/sysconfig/network" || die 'Missing target network directory\n'
     cat >"${TARGET}/etc/sysconfig/network/ifcfg-eth0" <<EOF
 BOOTPROTO='dhcp4'
 STARTMODE='auto'
@@ -216,7 +216,7 @@ get_os_type
 if test "$NIC_COUNT" -gt 0 && test -n "$OS_TYPE"; then
     ${OS_TYPE}_setup
 else
-    log_error 'Unsupported OS_TYPE'
+    die 'Unsupported OS_TYPE\n'
 fi
 
 cleanup
diff --git a/example/hooks/overlays b/example/hooks/overlays
--- a/example/hooks/overlays
+++ b/example/hooks/overlays
@@ -24,11 +24,11 @@ set -e
 . ./common.sh
 debug set -x
 
-test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
+test -d "$TARGET" || die 'Missing target directory\n'
 
 if test -n "$OVERLAY"; then
     overlay="${OVERLAYS_DIR}/$OVERLAY"
-    test -d "$overlay" || { log_error "$overlay not found"; exit 1; }
+    test -d "$overlay" || die '"%s" not found\n' "$overlay"
     # copy overlay files into target instance
     cp -ax "$overlay"/* "$TARGET"
 fi
diff --git a/example/hooks/zz_ddns b/example/hooks/zz_ddns
--- a/example/hooks/zz_ddns
+++ b/example/hooks/zz_ddns
@@ -28,7 +28,7 @@ FQDN="$INSTANCE_NAME"
 SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
 RENAME=''
 
-test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
+test -d "$TARGET" || die 'Missing target directory\n'
 
 while getopts 'r' _opt; do
     ! test 'r' = "$_opt" || RENAME='true'
@@ -42,8 +42,7 @@ debian_setup() {
     elif test -f "${TARGET}/etc/dhcp3/dhclient.conf"; then
         _dhclient_conf="${TARGET}/etc/dhcp3/dhclient.conf"
     else
-        log_error 'Missing dhclient.conf file'
-        exit 1
+        die 'Missing dhclient.conf file\n'
     fi
 
     if test -n "$FQDN" && test -z "$RENAME"; then
@@ -54,7 +53,7 @@ debian_setup() {
 }
 
 redhat_setup() {
-    test -f "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" || { log_error 'Missing ifcfg-eth0 file'; exit 1; }
+    test -f "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" || die 'Missing ifcfg-eth0 file\n'
     if test -n "$FQDN" && test -z "$RENAME"; then
         printf 'DHCP_HOSTNAME=%s' "$SHORT_NAME" >>"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0"
     else
@@ -62,9 +61,9 @@ redhat_setup() {
     fi
 }
 
-gentoo_setup() { log_error 'no action needed for ddns'; }
+gentoo_setup() { verbprint 'no action needed for ddns\n'; }
 
-suse_setup() { log_error 'untested for suse'; }
+suse_setup() { verbprint 'untested for suse\n'; }
 
 # Main
 get_os_type
@@ -72,5 +71,5 @@ get_os_type
 if test $NIC_COUNT -gt 0 && test -n "$OS_TYPE"; then
     "${OS_TYPE}_setup"
 else
-    log_error 'Unsupported OS_TYPE'
+    die 'Unsupported OS_TYPE\n'
 fi
diff --git a/export b/export
--- a/export
+++ b/export
@@ -53,7 +53,7 @@ else
         # upcoming commit)
         dev="$(eval "echo \${$(echo ${_fs}_dev)"})"
         vol_type="$(eval echo \$vol_type_${_fs})"
-        test -n "$vol_type" || test -z "$dev" || { log_error "Unable to find $_fs filesystem type at $dev"; exit 1; }
+        test -n "$vol_type" || test -z "$dev" || die 'Unable to find %s filesystem type at %s\n' "$_fs" "$dev"
         if test -n "$dev"; then
             case "$vol_type" in
                 ext3|ext2|ext4)
@@ -61,8 +61,7 @@ else
                     CLEANUP+=("rm -f \"${TARGET}/${_fs}.dump\"")
                     ;;
                 *)
-                    log_error "$_fs is not a supported filesystem. Please use ext{2,3,4}"
-                    exit 1
+                    die '%s is not a supported filesystem. Please use ext{2,3,4}\n' "$_fs"
                     ;;
             esac
         fi
