Rewrite of "tools"
* extensive rewrite of user "tools"
* tweaks of some common functions to work more generically (and be
  usable by hooks and tools)
* some minor bugfixes discovered along the way
* only use verbprint ($VERBOSE) in tools, avoid confusion with $IMAGE_DEBUG

diff --git a/common.sh.in b/common.sh.in
--- a/common.sh.in
+++ b/common.sh.in
@@ -49,7 +49,7 @@ printout() { printf "$@" | sed -e "s/^/${SCRIPT_NAME}: /"; }
 
 printerr() { printout "$@" >&2; }
 
-verbprint() { test 0 -eq $VERBOSE || printerr "$@"; }
+verbprint() { test -z "$VERBOSE" || test 0 -eq $VERBOSE || printerr "$@"; }
 
 die() { printerr "$@"; exit 1; }
 
@@ -102,44 +102,45 @@ $CLEANUP"
     esac
     case "$_cleanup_action" in
         init|pop|push|shift|unshift)
-            trap 'cleanup' EXIT || :
+            trap 'cleanup || :' EXIT || :
             ;;
     esac
     :
 }
 
-rmdir_disk0_temp() { # optional: 'dump|'
-    ! test 'dump' = "$1" || rm -rf "$DUMPDIR"
+mkdir_dumpdir_temp() {
+    DUMPDIR="`mktemp -d --tmpdir="${EXPORT_DIR:-${TMPDIR:-/tmp}}"`"
+    cleanup push "rmdir \"$DUMPDIR\""
+}
+
+rmdir_disk0_temp() {
     rmdir "$TARGET"
     TARGET="$OLD_TARGET"
     OLD_TARGET=''
     export TARGET
 }
 
-mkdir_disk0_temp() { # optional: 'dump|'
-    ! test 'dump' = "$1" || DUMPDIR="`mktemp -d --tmpdir="${EXPORT_DIR:-${TMPDIR:-/tmp}}"`"
+mkdir_disk0_temp() {
     OLD_TARGET="$TARGET"
     TARGET="`mktemp -d --tmpdir="${EXPORT_DIR:-${TMPDIR:-/tmp}}"`"
     export TARGET
-    cleanup push "rmdir_disk0_temp \"$1\""
+    cleanup push 'rmdir_disk0_temp'
 }
 
-unmount_disk0() { # optional: 'temp|' 'dump|'
+unmount_disk0() {
     sync
     test -z "$boot_dev" || umount "${TARGET}/boot"
     umount "${TARGET}/sys" 2>/dev/null || :
     umount "$TARGET"
-    ! test 'temp' = "$1" || rmdir_disk0_temp "$2"
 }
 
-mount_disk0() { # optional: 'temp|' 'dump|'
-    ! test 'temp' = "$1" || mkdir_disk0_temp "$2"
-    mount "$root_dev" "$TARGET"
+mount_disk0() { # optional: 'readonly'
+    mount `! test 'readonly' = "$1" || printf -- '-o ro'` "$root_dev" "$TARGET"
     if test -n "$boot_dev"; then
         $MKDIR_P "${TARGET}/boot"
-        mount "$boot_dev" "${TARGET}/boot"
+        mount `! test 'readonly' = "$1" || printf -- '-o ro'` "$boot_dev" "${TARGET}/boot"
     fi
-    cleanup push "unmount_disk0 \"$1\" \"$2\""
+    cleanup push "unmount_disk0"
 }
 
 unlosetup_blockdev() {
@@ -516,16 +517,60 @@ format_disk0_parted() {
     test -n "$KERNEL_PATH" || _parted_cmd "$_disk0" 'set' 1 'boot' 'on'
 }
 
+qcow_create() { "$QEMU_IMG" convert -O 'qcow2' -c "$BLOCKDEV" "$1" >/dev/null; }
+
+qcow_extract() { "$QEMU_IMG" convert -O 'host_device' "$1" "$BLOCKDEV" >/dev/null; }
+
+dump_create() {
+    _prefix="${1%root.dump}"
+    for _devname in 'boot' 'root'; do
+        eval "_dev=\"\${${_devname}_dev:-`printf '%s' "$_devname" | tr '[a-z]' '[A-Z]'`_DEV}\""
+        if test -z "$_dev"; then
+            test 'root' = "$_devname" || continue
+            die '%s_dev device doesn'\''t exist\n' "$_devname"
+        fi
+        _fs="`get_fs "$_dev"`"
+        case "$_fs" in
+            ext2|ext3|ext4)
+                "$DUMP" -0 -q -z9 -f "${_prefix}${_devname}.dump" "$_dev" >/dev/null
+                ;;
+            '')
+                die 'Unable to find filesystem type at "%s"\n' "$_dev"
+                ;;
+            *)
+                die '%s is not a supported filesystem. Please use ext{2,3,4}\n' "$_fs"
+                ;;
+        esac
+    done
+}
+
 dump_extract() {
-    _root_dump="${root_dump:-${IMAGE_FILE:-${DUMPDIR}/root.dump}}"
-    _boot_dump="${_root_dump%root.dump}boot.dump"
+    _prefix="${1$root.dump}"
     rm -rf "${TMPDIR:-/tmp}/rst"* # clean up any previous restore runs
-    test -f "$_root_dump" || die 'Can'\''t find image file "%s"\n' "$_root_dump"
-    ( cd "$TARGET" && restore -r -y -f "$_root_dump" >/dev/null )
+    test -f "${_prefix}root.dump" || die 'Can'\''t find image file "%s"\n' "${_prefix}root.dump"
+    ( cd "$TARGET" && restore -r -y -f "${_prefix}root.dump" >/dev/null )
     if test -n "$boot_dev"; then
-        test -f "$_boot_dump" || die 'Can'\''t find image file "%s"\n' "$_boot_dump"
-        ( cd "${TARGET}/boot" && restore -r -y -f "$_boot_dump" >/dev/null )
+        test -f "${_prefix}boot.dump" || die 'Can'\''t find image file "%s"\n' "${_prefix}boot.dump"
+        ( cd "${TARGET}/boot" && restore -r -y -f "${_prefix}boot.dump" >/dev/null )
     fi
+}
+
+tarball_create() {
+    # TODO: put pigz in autoconf as $PIGZ
+    if test -x /usr/bin/pigz; then
+        tar -I /usr/bin/pigz --numeric-owner -c -C "$TARGET" -f "$1" .
+    else
+        tar -z --numeric-owner -c -C "$TARGET" -f "$1" .
+    fi >/dev/null
+}
+
+tarball_extract() {
+    # TODO: put pigz in autoconf as $PIGZ
+    if test -x /usr/bin/pigz; then
+        tar -I /usr/bin/pigz --numeric-owner -x -p -C "$TARGET" -f "$1" .
+    else
+        tar -z --numeric-owner -x -p -C "$TARGET" -f "$1" .
+    fi >/dev/null
 }
 
 mkfs_disk0() {
@@ -628,7 +673,7 @@ setup_console() {
                     sed --follow-symlinks -i -e 's/.*T0.*/T0:23:respawn:\/sbin\/getty -L ttyS0 115200 vt100/' "${TARGET}/etc/inittab"
                     ;;
                 *)
-                    verbprint 'No support for your OS in instance-image, skipping...\n'
+                    printerr 'No support for your OS in instance-image, skipping...\n'
                     ;;
             esac
             ;;
@@ -645,13 +690,24 @@ filesystem_relabel() {
         fedora|centos|redhat)
             # we have to force a filesystem relabeling for SELinux after messing
             # around with the filesystem in fedora
-            verbprint 'Enforce an automatic relabeling in the initial boot process...\n'
+            printerr 'Enforce an automatic relabeling in the initial boot process...\n'
             touch "${TARGET}/.autorelabel"
             ;;
     esac
 }
 
 download_imagefile() {
+    case "$IMAGE_TYPE" in
+        tarball)
+            IMG_EXT='.tar.gz'
+            ;;
+        qemu)
+            IMG_EXT='.img'
+            ;;
+        dump)
+            IMG_EXT='-root.dump'
+            ;;
+    esac
     IMAGE_FILENAME="${IMAGE_NAME}-${ARCH}$IMG_EXT"
     IMAGE_FILE="${CACHE_DIR}/$IMAGE_FILENAME"
     if test -n "$IMAGE_URL"; then
@@ -704,6 +760,7 @@ check_os_variant() {
 source_os_variant() { ! test -f "$VARIANT_CONFIG" || . "$VARIANT_CONFIG"; }
 
 change_hostname() {
+    # TODO: systemd needs more changed ("machine-name", etc)
     case "$OS_TYPE" in
         debian)
             HNAME="${TARGET}/etc/hostname"
@@ -764,6 +821,7 @@ Instance has a different hostname "%s"\n' "$old_name" "$instance" "$OLD_HNAME"
 
 get_api10_parameters() {
     instance="$INSTANCE_NAME"
+    old_name="$OLD_INSTANCE_NAME"
     case "$SCRIPT_NAME" in
         export)
             BLOCKDEV="$EXPORT_DEVICE"
@@ -775,7 +833,6 @@ get_api10_parameters() {
             BLOCKDEV="$DISK_0_PATH"
             ;;
     esac
-    old_name="$OLD_INSTANCE_NAME"
 }
 
 get_api20_parameters() {
diff --git a/tools/gnt-disk-tool.in b/tools/gnt-disk-tool.in
--- a/tools/gnt-disk-tool.in
+++ b/tools/gnt-disk-tool.in
@@ -1,7 +1,9 @@
 #!/bin/sh
 
-# Copyright (C) 2012 Oregon State University (ganeti-image.in)
+# Copyright (C) 2012 Oregon State University
 # Copyright (C) 2013, 2014, 2015 GRNET S.A.
+#
+# (originally named ganeti-image.in)
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,91 +24,172 @@ set -e
 test -z "$GANETI_DEBUG" || set -x
 
 # presets
-SUBCOMMAND='make-image'
 IMAGE_TYPE=''
 IMAGE_DIR=''
 IMAGE_NAME=''
 ARCH=''
-SCRIPT_NAME="$(basename "$0")"
+MAP=0
+MOUNT=0
+READONLY=0
+RESIZE=''
+SUBCOMMAND=''
 INSTANCE_NAME=''
-HOSTNAME="`hostname`"
+SCRIPT_NAME="$(basename "$0")"
+VERBOSE=0
 
 # functions
-run_help() {
+usage() {
     cat <<EOF
-Usage: $SCRIPT_NAME [OPTIONS] INSTANCE_NAME
+Usage: $SCRIPT_NAME SUBCOMMAND [OPTIONS] INSTANCE_NAME
 
 Wrapper for ganeti-instance-image sub-commands.
 
 ARGS:
+ SUBCOMMAND       Which subcommand to use (make-image, apply-image,
+                  mount-disks, umount-disks, show, shrink, expand, shell,
+                  chroot, noop)
  INSTANCE_NAME    Name of the instance
 
 OPTIONS:
- -c SUBCOMMAND    Which subcommand to use: (def: make-image)
-                   make-image, mount-disks, umount-disks
- -t IMAGE_TYPE    Type of image, either: tarball, dump, or qemu
- -d IMAGE_DIR     Path of where to put the image
- -n IMAGE_NAME    Name of the image
- -a ARCH          Architecture of the image
+ -h, --help             : This output
+ -v, --verbose          : Verbose output
+ -t, --type IMAGE_TYPE  : Type of image, either: tarball, dump, or qemu
+ -d, --dir IMAGE_DIR    : Path of where to put the image
+ -n, --name IMAGE_NAME  : Name of the image
+ -a, --arch ARCH        : Architecture of the image
+ -m, --map              : Map partitions
+ -M, --mount            : Mount/Unmount filesystems to a tempdir
+ -r, --readonly         : Ensure any mounting is readonly
+ -R, --resize OBJECT    : OBJECT:
+                           filesystem: resize FS (default)
+                           partition: resize FS and partition (if possible)
+                           disk: resize FS, partition and disk (if possible)
 
-This utility must be used on the master node. All optional args will
-have defaults if you do not set them.
+ACTIONS:
+
+ make-image             : Make image file for the instance's disks
+ apply-image            : Apply an image file to an instance's disks
+ mount-disks            : Mount the instance's disks to a tempdir
+ umount-disks           : Unmount the instance's disks from a tempdir
+ show                   : Show "fdisk -l", with -m also "dumpe2fs -h",
+                          with -M also "df"
+ shrink                 : Shrink instance's root FS to minimal size
+ expand                 : Expand instance's root FS to maximal size
+ shell                  : Drop to interactive shell after setting up disk (and
+                          maps/mounts depending on -m, -M)
+ chroot                 : Same as "shell" but chroot to mounted root FS
+                          (forces -m and -M)
+ noop (or '')           : Just does setup/tear-down of disk (and maps/mounts
+                          depending on -m, -M)
+
+This utility must be used on the master node. All optional args will have
+defaults if you do not set them.
 EOF
 }
 
+vm_is_running() { test 'running' = "`gnt-instance list -o status --no-headers "$INSTANCE_NAME"`"; }
+printerr() { printf "$@" | sed -e "s/^/${SCRIPT_NAME}: /" >&2; }
+die() { printerr "$@"; exit 1; }
+croak() { usage >&2; die "$@"; }
+verbprint() { test 0 -eq $VERBOSE || printerr "$@"; }
+
+# get and sanity-check subcommand
+case "$1" in
+    make-image|apply-image|mount-disks|umount-disks|show|shrink|expand|shell|chroot|noop)
+        SUBCOMMAND="$1"
+        shift
+        ;;
+    -h|--help)
+        exec "$0" -h
+        ;;
+    *)
+        croak 'Subcommand "%s" not implemented\n' "$1"
+        ;;
+esac
+
 # getopts
-while getopts "c:t:d:n:a:h" _opt; do
-    case "$_opt" in
-        c)
-            SUBCOMMAND="$OPTARG"
-            ;;
-        t)
-            IMAGE_TYPE="$OPTARG"
-            ;;
-        d)
-            IMAGE_DIR="$OPTARG"
-            ;;
-        n)
-            IMAGE_NAME="$OPTARG"
-            ;;
-        a)
-            ARCH="$OPTARG"
-            ;;
-        h)
-            run_help
+while test $# -gt 0; do
+    case "$1" in
+        -h|--help)
+            usage
             exit 0
             ;;
+        -v|--verbose)
+            VERBOSE=1
+            shift
+            ;;
+        -t|--type)
+            IMAGE_TYPE="$2"
+            shift
+            ;;
+        -d|--dir)
+            IMAGE_DIR="$2"
+            shift 2
+            ;;
+        -n|--name)
+            IMAGE_NAME="$2"
+            shift 2
+            ;;
+        -a|--arch)
+            ARCH="$2"
+            shift 2
+            ;;
+        -m|--map)
+            MAP=1
+            shift
+            ;;
+        -M|--mount)
+            MOUNT=1
+            shift
+            ;;
+        -r|--readonly)
+            READONLY=1
+            shift
+            ;;
+        -R|--resize)
+            RESIZE="$2"
+            shift 2
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            croak 'Unknown option "%s"\n' "$1"
+            ;;
         *)
-            run_help
-            exit 1
+            break
             ;;
     esac
 done
+test 0 -eq $MOUNT || MAP=1
 INSTANCE_NAME="$1"
+shift
 
 # sanity checks
-test -n "$INSTANCE_NAME" || { printf 'Error: Instance name not set\n' >&2; exit 1; }
-case "$SUBCOMMAND" in
-    make-image|mount-disks|umount-disks)
-        :
-        ;;
-    *)
-        printf 'Subcommand "%s" not implemented\n' "$SUBCOMMAND" >&2
-        exit 1
-        ;;
-esac
+test -n "$INSTANCE_NAME" || croak 'Instance name not set\n'
 case "$IMAGE_TYPE" in
     tarball|dump|qemu|'')
         :
         ;;
     *)
-        printf 'Error: Incorrect type "%s" set\n' "$TYPE" >&2
-        exit 1
+        croak 'Unknown image-type "%s" (not qemu|tarball|dump)\n' "$IMAGE_TYPE"
         ;;
 esac
-test "x`gnt-cluster getmaster`" = "x$HOSTNAME" || \
-    { printf 'ERROR: Command must be run from master node\n'; exit 1; }
+case "$RESIZE" in
+    filesystem|partition|disk|'')
+        :
+        ;;
+    *)
+        croak 'Unknown resize object type "%s" (not filesystem|partition|disk)\n' "$RESIZE"
+        ;;
+esac
+MASTER_NODE="`gnt-cluster getmaster`"
+HOSTNAME="`hostname -f`"
+test "x$MASTER_NODE" = "x$HOSTNAME" || \
+    die 'ERROR: Command must be run from master node "%s", not "%s"\n' "$MASTER_NODE" "$HOSTNAME"
 
+## TODO: $ARCH might be able to be set from ganeti here, rather than manually by flag?
 # env vars
 output="$(gnt-instance activate-disks "$INSTANCE_NAME" | grep ':disk/0:')"
 trap "gnt-instance deactivate-disks \"$INSTANCE_NAME\"" EXIT
@@ -120,8 +203,6 @@ INSTANCE_HV_kernel_path="`printf '%s' "$info" | cut -d\| -f4`"
 OS_API_VERSION=20
 
 # main
-printf 'Creating image with type "%s" from "%s" in "%s" from node "%s"\n' \
-    "$IMAGE_TYPE" "$INSTANCE_NAME" "$IMAGE_DIR" "$NODE" >&2
 eval_string="
     DISK_0_PATH=\"$DISK_0_PATH\"
     OS_VARIANT=\"$OS_VARIANT\"
@@ -129,16 +210,114 @@ eval_string="
     DISK_COUNT=\"$DISK_COUNT\"
     INSTANCE_HV_kernel_path=\"$INSTANCE_HV_kernel_path\"
     OS_API_VERSION=20
-    export DISK_0_PATH OS_VARIANT HYPERVISOR DISK_COUNT INSTANCE_HV_kernel_path OS_API_VERSION
-    \"@osdir@/@osname@/tools/$SUBCOMMAND\" `
-        test -z "$IMAGE_TYPE" || printf '-t "%s" ' "$IMAGE_TYPE"
-        test -z "$IMAGE_DIR" || printf '-d "%s" ' "$IMAGE_DIR"
-        test -z "$IMAGE_NAME" || printf '-n "%s" ' "$IMAGE_TYPE"
-        test -z "$ARCH" || printf '-a "%s" ' "$ARCH"
-    ` \"$INSTANCE_NAME\"
+    VERBOSE=\"$VERBOSE\"
+    export DISK_0_PATH OS_VARIANT HYPERVISOR DISK_COUNT INSTANCE_HV_kernel_path OS_API_VERSION VERBOSE
+    \"@osdir@/@osname@/tools/$SUBCOMMAND\" \
 "
+case "$SUBCOMMAND" in
+    make-image)
+        verbprint 'Creating image with type "%s" from "%s" in "%s" from node "%s"\n' \
+            "$IMAGE_TYPE" "$INSTANCE_NAME" "$IMAGE_DIR" "$NODE"
+        eval_string="$eval_string`
+            test -z "$IMAGE_TYPE" || printf -- ' -t "%s"' "$IMAGE_TYPE"
+            test -z "$IMAGE_DIR" || printf -- ' -d "%s"' "$IMAGE_DIR"
+            test -z "$IMAGE_NAME" || printf -- ' -n "%s"' "$IMAGE_TYPE"
+            test -z "$ARCH" || printf -- ' -a "%s"' "$ARCH"
+        `"
+        ;;
+    apply-image)
+        verbprint 'Applying image to "%s" from "%s" on node "%s"\n' \
+            "$INSTANCE_NAME" "$IMAGE_DIR" "$NODE"
+        eval_string="$eval_string`
+            test -z "$IMAGE_DIR" || printf -- ' -d "%s"' "$IMAGE_DIR"
+            test -z "$IMAGE_NAME" || printf -- ' -n "%s"' "$IMAGE_TYPE"
+            test -z "$ARCH" || printf -- ' -a "%s"' "$ARCH"
+        `"
+        ;;
+    mount-disks)
+        verbprint 'Mounting disks %sfor instance "%s" on node "%s"\n' \
+            "`test 0 -eq $READONLY || printf 'readonly '`" "$INSTANCE_NAME" "$NODE"
+        eval_string="$eval_string`test 0 -eq $READONLY || printf -- ' -r'`"
+        ;;
+    umount-disks)
+        verbprint 'Unmounting disks for instance "%s" on node "%s"\n' \
+            "$INSTANCE_NAME" "$NODE"
+        ;;
+    show)
+        verbprint 'Showing partition table%s for instance "%s"\n' \
+            "`test 0 -eq $MAP || printf ', partition headers'
+              test 0 -eq $MOUNT || printf ', filesystem usage'`" "$INSTANCE_NAME"
+        eval_string="$eval_string`
+            test 0 -eq $MAP || printf -- ' -m'
+            test 0 -eq $MOUNT || printf -- ' -M'
+            test 0 -eq $READONLY || printf -- ' -r'
+        `"
+        ;;
+    shrink|expand)
+        verbprint '%sing FS%s for instance "%s"\n' \
+            "`printf '%s' "$SUBCOMMAND" | tr '[a-z]' '[A-Z]'`" \
+            "`case "$RESIZE" in
+                  disk)
+                      printf ', partition, disk'
+                      ;;
+                  partition)
+                      printf ', partition'
+                      ;;
+              esac`" \
+            "$INSTANCE_NAME"
+        eval_string="$eval_string`test -z "$RESIZE" || printf -- ' -R "%s"' "$RESIZE"`"
+        ;;
+    shell)
+        verbprint 'Setting up disk%s then dropping to shell for "%s"\n' \
+            "`test 0 -eq $MAP || printf ', partitions'
+              test 0 -eq $MOUNT || printf ', filesystems'`" \
+            "$INSTANCE_NAME"
+        eval_string="$eval_string`
+            test 0 -eq $MAP || printf -- ' -m'
+            test 0 -eq $MOUNT || printf -- ' -M'
+            test 0 -eq $READONLY || printf -- ' -r'
+        `"
+        ;;
+    chroot)
+        verbprint 'Setting up disk, partitions, filesystems%s then chrooting in for "%s"\n' \
+            "`test 0 -eq $READONLY || printf ' (readonly)'`" \
+            "$INSTANCE_NAME"
+        eval_string="$eval_string`test 0 -eq $READONLY || printf -- ' -r'`"
+        ;;
+    noop)
+        verbprint 'Doing noop%s for "%s"\n' \
+            "`test 0 -eq $MAP || printf ', mapping partitions'
+              if test 1 -eq $MOUNT; then
+                  printf ', mounting filesystems'
+                  test 0 -eq $READONLY || printf ' (readonly)'
+              fi`" \
+            "$INSTANCE_NAME"
+        eval_string="$eval_string`
+            test 0 -eq $MAP || printf -- ' -m'
+            test 0 -eq $MOUNT || printf -- ' -M'
+            test 0 -eq $READONLY || printf -- ' -r'
+        `"
+        ;;
+esac
+eval_string="$eval_string \"$INSTANCE_NAME\""
+
+if vm_is_running; then
+    case "$SUBCOMMAND" in
+        noop|show)
+            if test 1 -eq $MAP; then
+                trap - EXIT
+                die 'VM is running. Can not perform "%s" while (re)mapping the partitions\n' "$SUBCOMMAND"
+            fi
+            ;;
+        *)
+            trap - EXIT
+            die 'VM is running. Can not perform "%s"\n' "$INSTANCE_NAME"
+            ;;
+    esac
+fi
 if test "x$NODE" = "x$HOSTNAME"; then
     eval "$eval_string"
 else
-    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$NODE" "$eval_string"
+    ssh -o StrictHostKeyChecking=no "$NODE" "$eval_string"
 fi
+test ! vm_is_running || trap - EXIT
