Syntax cleanups/fixes (no semantic changes)
* Only change syntactic aspects of code for consistency/readability/robustness,
  and so I can better work on the following commits - no externally significant
  functional changes in this commit (have kept all these changes in a separate
  commit to not drown future commit diffs with noise).

* (robustness) Separate out sed flags (incidentally in at least a few places
  this actually fixes a bug where - for at least GNU sed - using '-ie' creates
  copies of files named with an appended 'e' rather than inplace updating the
  file!)

* (robustness) Ensure all in-place sed-replacements follow symlinks

* (robustness) Use mktemp and $TMPDIR in a more system-friendly manner

* (robustness,readability) Move defining executable paths to top files

* (robustness,portability) Export variables on separate lines from declaration

* (readability) Standardise formatting/layout/indentation.

* (readability) Replace e.g. "cmd '\-args" -> "cmd -- -args"'

* (readability) Use 'test' instead of '[' and ']', etc (Ada-style is better
  then code-golf-style).

* (readability) Remove unnecessary braces in var-expansions:
  + "as ${shown} in ${this} $example" ==> "as $shown in $this $example"

* (readability) Remove unneeded comment lines (where logic is already obvious)

* (readability,robustness) Remove unnecessary $target=$TARGET in functions
  (also for $blockdev=$BLOCKDEV, and one use of $fs=$FILESYSTEM), make related
  functions parameter-less

* (robustness,readability) Remove redundant test from conditionals

* (robustness) Remove unnecessary subshell usage

* (portability) Use _var=x instead of 'local var=x'

* (readability) Rename vars more indicatively (e.g. $filesystem_dev_base ->
  $filesystem_dev1_base, etc)

* (robustness,portability) Replace gotcha-prone commands e.g. echo ==> printf.

* (robustness) Only use double-quotes around variable expansions, otherwise use
  single-quotes, e.g.
   "a \\t silly\\n\\n\"example\"" => 'a \t silly\n\n"example"'

* (robustness) Rewrite tests to avoid issues like for $x='-w':
   + 'test "$x" = "Y"' ==> 'test "Y" = "$x"' or 'test "x$x" = "x$z"

* (readability) Use <<here-docs for multiline output rather than multiple
  echos.

* (readability) Shrink small/single-op logic-blocks to oneliners where
  sensible.

* (portability) Prefer portable variable string-transforms where possible.

* (robustness) Replace 'echo/printf' with 'log_error' where the latter was intended.

* (robustness) Make some log messages more specific.

* (robustness) Quote variables wherever possible.

* (robustness) Use 'eval "$cmd [args]' instead of just '$cmd [args]' where
  there are possibly embedded quotes to expand.

* (robustness) Eval the cleanup call when the variable is substituted, so args
  can be quoted inside all stored cleanup commands.

* (robustness,portability) Rewrite shell-implementation-specific bits of code
  e.g. '$((' -> `expr`, '$RANDOM' -> 'od ... /dev/urandom', etc.

* (readability) Remove redundant 'exit 0', 'cd $OLDPWD', etc at end of files

* (readability,robustness) Remove redundant 'var=""' where the var is also
  explicitly defined later.

* (readability,robustness) Remove redundant '|| exit 1' when 'set -e' is used
  anyway.

* (readability) Replace if-x/elif-x/elif-x.. with case/x/x/x.. where possible.

* (robustness) Prevent recursive copies crossing filesystem boundaries

* (robustness,readability) Standardise prefixes of replaced variable names -
  was a mix of OLD_ and ORIGINAL_, now just OLD_

diff --git a/create b/create
--- a/create
+++ b/create
@@ -21,151 +21,137 @@ set -e
 . ./common.sh
 debug set -x
 
-if [ "$IMAGE_TYPE" = "tarball" ] ; then
-    IMG_EXT=".tar.gz"
-elif [ "$IMAGE_TYPE" = "qemu" ] ; then
-    IMG_EXT=".img"
-elif [ "$IMAGE_TYPE" = "dump" ] ; then
-    IMG_EXT="-root.dump"
-fi
+RUN_PARTS="`which run-parts`"
+case "$IMAGE_TYPE" in
+    tarball)
+        IMG_EXT='.tar.gz'
+        ;;
+    qemu)
+        IMG_EXT='.img'
+        ;;
+    dump)
+        IMG_EXT='-root.dump'
+        ;;
+esac
 
-if [ ! -z "$IMAGE_URL" ] ; then
-    cd ${CACHE_DIR}
-    if [ ! -e ${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT} ]; then
-        $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}${IMG_EXT}" >/dev/null 2>/dev/null\
-        || (log_error "Failed to find the image on ${IMAGE_URL}"; exit 1)
+if ! test -z "$IMAGE_URL"; then
+    cd "$CACHE_DIR"
+    if ! test -e "${CACHE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT"; then
+        $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}$IMG_EXT" >/dev/null 2>/dev/null || \
+            { log_error "Failed to find the image on $IMAGE_URL"; exit 1; }
     fi
-    if [ "$IMG_VERIFY" = "yes" ]; then
-        $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null 2>/dev/null\
-        || (log_error "Failed to find the checksum file"; exit 1)
-        $SHA1SUM -c "${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null \
-        || (log_error "Image doesn't match checksum!"; exit 1)
+    if test 'yes' = "$IMG_VERIFY"; then
+        $WGET "${IMAGE_URL}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null 2>/dev/null || \
+            { log_error 'Failed to find the checksum file'; exit 1; }
+        "$SHA1SUM" -c "${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig" >/dev/null || \
+            { log_error 'Image doesn'\''t match checksum!'; exit 1; }
     fi
-    if [ $IMG_CLEANUP="yes" ]; then
-        CLEANUP+=("rm ${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT} ${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig")
-    fi
-    IMAGE_FILE="${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT}"
-    cd $OLDPWD
+    ! test 'yes' = "$IMG_CLEANUP" || \
+        CLEANUP+=("rm -f \"${CACHE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT\" \"${CACHE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT}.sig\"")
+    IMAGE_FILE="${CACHE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT"
+    cd "$OLDPWD"
 else
-    IMAGE_FILE="${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}${IMG_EXT}"
+    IMAGE_FILE="${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}$IMG_EXT"
 fi
 
-if [ "$IMAGE_TYPE" = "dump" ] ; then
+if test 'dump' = "$IMAGE_TYPE"; then
     # Workaround for restore's non-unique /tmp/rstdir* and /tmp/rstmode*
-    export TMPDIR=$(mktemp -d /tmp/${INSTANCE_NAME}_XXXXXXXX)
-    CLEANUP+=("rmdir --ignore-fail-on-non-empty $TMPDIR")
+    TMPDIR="$(mktemp -d --tmpdir "${INSTANCE_NAME}_XXXXXXXX")"
+    export TMPDIR
+    CLEANUP+=("rmdir --ignore-fail-on-non-empty \"$TMPDIR\"")
 fi
 
-if [ "$CDINSTALL" = "no" ] ; then
+if test 'no' = "$CDINSTALL"; then
     # If the target device is not a real block device we'll first losetup it.
     # This is needed for file disks.
-    if [ ! -b $blockdev ]; then
-      ORIGINAL_BLOCKDEV=$blockdev
-      blockdev=$($LOSETUP -sf $blockdev)
-      CLEANUP+=("$LOSETUP -d $blockdev")
+    if ! test -b "$BLOCKDEV"; then
+        OLD_BLOCKDEV="$BLOCKDEV"
+        BLOCKDEV="$("$LOSETUP" -sf "$BLOCKDEV")"
+        CLEANUP+=("\"$LOSETUP\" -d \"$BLOCKDEV\"")
     fi
 
-    DISK_SIZE="$(expr `${BLOCKDEV_CMD} --getsize64 $blockdev` / 1048576)"
+    DISK_SIZE="$(expr `"$BLOCKDEV_CMD" --getsize64 "$BLOCKDEV"` / 1048576)"
 
-    if [ "${SWAP}" = "yes" ]; then
-        if [ -z "$SWAP_SIZE" ] ; then
-            log_error "SWAP_SIZE not set however SWAP is enabled"
-            exit 1
-        elif [ "${SWAP_SIZE}" -gt "${DISK_SIZE}" ] ; then
-            log_error "SWAP_SIZE larger than system disk size: "
-            log_error "  ${SWAP_SIZE}MB swap > ${DISK_SIZE}MB system disk"
-            exit 1
-        fi
+    if test 'yes' = "$SWAP"; then
+        test -n "$SWAP_SIZE" || { log_error 'SWAP_SIZE not set however SWAP is enabled'; exit 1; }
+        test $SWAP_SIZE -le $DISK_SIZE || \
+            { log_error 'SWAP_SIZE larger than system disk size: '; log_error "  ${SWAP_SIZE}MB swap > ${DISK_SIZE}MB system disk"; exit 1; }
     fi
 
-    if [ ! -f "$IMAGE_FILE" ] ; then
-      log_error "Can't find image file: $IMAGE_FILE"
-      exit 1
-    fi
+    test -f "$IMAGE_FILE" || { log_error "Can't find image file: $IMAGE_FILE"; exit 1; }
 
     # If the image is tarball based, then we need to manually create the
     # volumes, filesystems, etc
-    if [ "${IMAGE_TYPE}" = "tarball" -o "${IMAGE_TYPE}" = "dump" ] ; then
+    if test 'tarball' = "$IMAGE_TYPE" || test 'dump' = "$IMAGE_TYPE"; then
         # Create 3 partitions, /boot, swap, & /
-        format_disk0 $blockdev
-    elif [ "${IMAGE_TYPE}" = "qemu" ] ; then
+        format_disk0 "$BLOCKDEV"
+    elif test 'qemu' = "$IMAGE_TYPE"; then
         # need a recent version of qemu for this
-        ${QEMU_IMG} convert ${IMAGE_FILE} -O host_device ${blockdev} > /dev/null
+        "$QEMU_IMG" convert "$IMAGE_FILE" -O 'host_device' "$BLOCKDEV" >/dev/null
     fi
 
     # deploying something like a windows image, skip the rest
-    if [ "${NOMOUNT}" = "yes" ] ; then
-      cleanup
-      exit 0
-    fi
+    ! test 'yes' = "$NOMOUNT" || { cleanup; exit 0; }
 
-    RUN_PARTS=`which run-parts`
-
-    if [ -n "$RUN_PARTS" -a -n "$PRE_CUSTOMIZE_DIR" -a -d "$PRE_CUSTOMIZE_DIR" ]; then
-        BLOCKDEV=$blockdev
+    if test -n "$RUN_PARTS" && test -d "$PRE_CUSTOMIZE_DIR"; then
         export TARGET SUITE BLOCKDEV IMAGE_TYPE
-        $RUN_PARTS $PRE_CUSTOMIZE_DIR
+        "$RUN_PARTS" "$PRE_CUSTOMIZE_DIR"
     fi
 
-    filesystem_dev=$(map_disk0 $blockdev)
-    CLEANUP+=("unmap_disk0 $blockdev")
-    root_dev=$(map_partition $filesystem_dev root)
-    boot_dev=$(map_partition $filesystem_dev boot)
-    swap_dev=$(map_partition $filesystem_dev swap)
+    filesystem_dev="$(map_disk0)"
+    CLEANUP+=('unmap_disk0')
+    root_dev="$(map_partition "$filesystem_dev" root)"
+    boot_dev="$(map_partition "$filesystem_dev" boot)"
+    swap_dev="$(map_partition "$filesystem_dev" swap)"
 
-    if [ "${IMAGE_TYPE}" = "tarball" -o "${IMAGE_TYPE}" = "dump" ] ; then
-        mkfs_disk0
-        root_uuid="$($VOL_ID $root_dev)"
-        [ -n "$boot_dev" ] && sleep 1 && boot_uuid="$($VOL_ID $boot_dev)"
-        [ -n "$swap_dev" ] && sleep 1 && swap_uuid="$($VOL_ID $swap_dev)"
-    fi
+    case "$IMAGE_TYPE" in
+        tarball|dump)
+            mkfs_disk0
+            root_uuid="$(eval "$VOL_ID \"$root_dev\"")"
+            test -n "$boot_dev" && sleep 1 && boot_uuid="$(eval "$VOL_ID \"$boot_dev\"")"
+            test -n "$swap_dev" && sleep 1 && swap_uuid="$(eval "$VOL_ID \"$swap_dev\"")"
+            ;;
+    esac
 
-    TARGET=`mktemp -d` || exit 1
-    CLEANUP+=("rmdir $TARGET")
+    TARGET="`mktemp -d`"
+    CLEANUP+=("rmdir \"$TARGET\"")
 
     # mount filesystems
-    mount_disk0 $TARGET
+    mount_disk0
 
-    if [ "${IMAGE_TYPE}" = "tarball" ] ; then
-        # unpack image
-        tar pzxf $IMAGE_FILE -C $TARGET
-    elif [ "${IMAGE_TYPE}" = "dump" ] ; then
-        root_dump="${IMAGE_FILE}"
-        ( cd ${TARGET}; restore -r -y -f ${root_dump} > /dev/null )
-
-        if [ -n "${boot_dev}" ] ; then
-            boot_dump="${IMAGE_FILE/root.dump/boot.dump}"
-            if [ ! -f "$boot_dump" ] ; then
-              log_error "Can't find image file: $boot_dump"
-              exit 1
+    case "$IMAGE_TYPE" in
+        tarball)
+            # unpack image
+            tar pzxf "$IMAGE_FILE" -C "$TARGET"
+            ;;
+        dump)
+            root_dump="$IMAGE_FILE"
+            ( cd "$TARGET"; restore -r -y -f "$root_dump" >/dev/null )
+            if test -n "$boot_dev"; then
+                boot_dump="${IMAGE_FILE%root.dump}boot.dump"
+                test -f "$boot_dump" || { log_error "Can't find image file: $boot_dump"; exit 1; }
+                ( cd "${TARGET}/boot"; restore -r -y -f "$boot_dump" >/dev/null )
             fi
-            ( cd ${TARGET}/boot; restore -r -y -f ${boot_dump} > /dev/null )
-        fi
-    fi
+            ;;
+    esac
 
-    if [ "${IMAGE_TYPE}" = "tarball" -o "${IMAGE_TYPE}" = "dump" ] ; then
-        setup_fstab $TARGET
-    fi
+    case "$IMAGE_TYPE" in
+        tarball|dump)
+            setup_fstab
+            ;;
+    esac
 
-    if [ "${INSTANCE_HV_serial_console}" = "True" ] ; then
-        setup_console $TARGET
-    fi
+    ! test 'True' = "$INSTANCE_HV_serial_console" || setup_console
 
-    filesystem_check $TARGET
+    filesystem_check
 
-    if [ -n "$RUN_PARTS" -a -n "$CUSTOMIZE_DIR" -a -d "$CUSTOMIZE_DIR" ]; then
-      TARGET=$TARGET
-      BLOCKDEV=$blockdev
-      ROOT_DEV=$root_dev
-      BOOT_DEV=$boot_dev
-      IMG_SSH_KEY_URL="$IMG_SSH_KEY_URL"
-      export TARGET SUITE BLOCKDEV ROOT_DEV BOOT_DEV IMAGE_TYPE IMG_SSH_KEY_URL
-      $RUN_PARTS $CUSTOMIZE_DIR
+    if test -n "$RUN_PARTS" && test -d "$CUSTOMIZE_DIR"; then
+        ROOT_DEV="$root_dev"; BOOT_DEV="$boot_dev"; IMG_SSH_KEY_URL="$IMG_SSH_KEY_URL"
+        export TARGET SUITE BLOCKDEV ROOT_DEV BOOT_DEV IMAGE_TYPE IMG_SSH_KEY_URL
+        "$RUN_PARTS" "$CUSTOMIZE_DIR"
     fi
 fi
 
 # execute cleanups
 cleanup
 trap - EXIT
-
-exit 0
diff --git a/example/hooks/grub b/example/hooks/grub
--- a/example/hooks/grub
+++ b/example/hooks/grub
@@ -20,23 +20,19 @@
 # This is an example script that configures, grub after installation. This
 # script assumes that grub has been installed onto the image already and a
 # working grub.conf exists. This is only enabled if using the tarball image
-# type. 
+# type.
 
 set -e
 . ./common.sh
 debug set -x
 
-if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
-    log_error "Missing target directory"
-    exit 1
-fi
+test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
 
 # Set disk based on type of hypervisor
-disk=""
-if [ "${HYPERVISOR}" = "kvm" ] ; then
-  disk="vda"
+if test 'kvm' = "$HYPERVISOR"; then
+    disk='vda'
 else
-  disk="xda"
+    disk='xda'
 fi
 
 if test -s "${TARGET}/boot/grub2/grub.cfg"; then
@@ -44,129 +40,123 @@ if test -s "${TARGET}/boot/grub2/grub.cfg"; then
 else
     boot_dir_internal='/boot/grub'
 fi
-boot_dir="${TARGET}${boot_dir_internal}"
+boot_dir="${TARGET}$boot_dir_internal"
 
 setup_disk_devs() {
-    root_part="${ROOT_DEV/*-/}"
-    boot_part="${BOOT_DEV/*-/}"
+    root_part="${ROOT_DEV##*-}"
+    boot_part="${BOOT_DEV##*-}"
 
-    mknod ${TARGET}/dev/${disk} b $(stat -L -c "0x%t 0x%T" $BLOCKDEV)
-    CLEANUP+=("rm -f ${TARGET}/dev/$disk")
+    mknod "${TARGET}/dev/$disk" b `stat -L -c '0x%t 0x%T' "$BLOCKDEV"`
+    CLEANUP+=("rm -f \"${TARGET}/dev/$disk\"")
 
-    mknod ${TARGET}/dev/${disk}${root_part} b $(stat -L -c "0x%t 0x%T" $ROOT_DEV)
-    CLEANUP+=("rm -f ${TARGET}/dev/${disk}${root_part}")
+    mknod "${TARGET}/dev/${disk}$root_part" b `stat -L -c '0x%t 0x%T' "$ROOT_DEV"`
+    CLEANUP+=("rm -f \"${TARGET}/dev/${disk}$root_part\"")
 
-    if [ -n "$BOOT_DEV" ] ; then
-        mknod ${TARGET}/dev/${disk}${boot_part} b $(stat -L -c "0x%t 0x%T" $BOOT_DEV)
-        CLEANUP+=("rm -f ${TARGET}/dev/${disk}${boot_part}")
+    if test -n "$BOOT_DEV"; then
+        mknod "${TARGET}/dev/${disk}$boot_part" b `stat -L -c '0x%t 0x%T' "$BOOT_DEV"`
+        CLEANUP+=("rm -f \"${TARGET}/dev/${disk}$boot_part\"")
     fi
 
     # setup minimal proc environment for grub2
-    $MKDIR_P ${TARGET}/proc/
-    cat > ${TARGET}/proc/mounts <<EOF
-/dev/${disk}${boot_part} /boot ${FILESYSTEM} rw,relatime,barrier=1,data=ordered 0 0
-/dev/${disk}${root_part} / ${FILESYSTEM} rw,relatime,barrier=1,data=ordered 0 0
+    $MKDIR_P "${TARGET}/proc"
+    cat >"${TARGET}/proc/mounts" <<EOF
+/dev/${disk}$boot_part /boot $FILESYSTEM rw,relatime,barrier=1,data=ordered 0 0
+/dev/${disk}$root_part / $FILESYSTEM rw,relatime,barrier=1,data=ordered 0 0
 EOF
-    CLEANUP+=("rm -r ${TARGET}/proc/mounts")
+    CLEANUP+=("rm -rf \"${TARGET}/proc/mounts\"")
 
-    cat > ${TARGET}/proc/devices <<EOF
+    cat >"${TARGET}/proc/devices" <<EOF
 Block devices:
 251 virtblk
 252 device-mapper
 EOF
-    CLEANUP+=("rm -r ${TARGET}/proc/devices")
-    cat > ${TARGET}/proc/misc << EOF
- 60 device-mapper
+    CLEANUP+=("rm -rf \"${TARGET}/proc/devices\"")
+    cat >"${TARGET}/proc/misc" <<EOF
+60 device-mapper
 EOF
-    CLEANUP+=("rm -r ${TARGET}/proc/misc")
+    CLEANUP+=("rm -rf \"${TARGET}/proc/misc\"")
 }
 
 add_devicemap() {
-    cat > "${boot_dir}/device.map" <<EOF
-(hd0) /dev/${disk}
+    cat >"${boot_dir}/device.map" <<EOF
+(hd0) /dev/$disk
 EOF
 }
 
-if [ "${IMAGE_TYPE}" != "qemu" ] && \
-   [ -z "${INSTANCE_HV_kernel_path}" -o \
-    "${INSTANCE_HV_kernel_path}" = "/bin/false" -o \
-    "${IMPORT_SCRIPT}" = "1" ] ; then
+if ! test 'qemu' = "$IMAGE_TYPE" && \
+    {
+        test -z "$INSTANCE_HV_kernel_path" || \
+            test '/bin/false' = "$INSTANCE_HV_kernel_path" || \
+            test 1 = "$IMPORT_SCRIPT"
+    }; then
     setup_disk_devs
     add_devicemap
 
-    if [ -e "${boot_dir}/menu.lst" ] ; then
-        grub="$(chroot ${TARGET} which grub)"
+    if test -e "${boot_dir}/menu.lst"; then
+        grub="$(chroot "$TARGET" which grub)"
         # install grub to the block device
-        chroot ${TARGET} ${grub} --batch --no-floppy \
-            --device-map=${boot_dir_internal}/device.map > /dev/null <<EOF
+        chroot "$TARGET" "$grub" --batch --no-floppy \
+            --device-map="${boot_dir_internal}/device.map" >/dev/null <<EOF
 root (hd0,0)
 setup (hd0)
 quit
 EOF
         # check to see if grub is using UUID's and replace if so
-        if [ -n "$(grep 'root=UUID' ${boot_dir}/menu.lst)" ] ; then
-            root_uuid="$($VOL_ID $ROOT_DEV)"
-            sed --follow-symlinks -ie "s/\(root=UUID=\)\([a-z0-9-]*\)/\1${root_uuid}/g" \
-                ${boot_dir}/menu.lst
+        if test -n "$(grep 'root=UUID' "${boot_dir}/menu.lst")"; then
+            root_uuid="$(eval "$VOL_ID \"$ROOT_DEV\"")"
+            sed --follow-symlinks -i -e 's/\(root=UUID=\)\([a-z0-9-]*\)/\1'"$root_uuid"'/g' "${boot_dir}/menu.lst"
         fi
         # additional kernel arguments for the instance
-        if [ -n "${KERNEL_ARGS}" ] ; then
-            sed --follow-symlinks -ie "s/\(.*kernel.*\)/\1 ${KERNEL_ARGS}/g" \
-                ${boot_dir}/menu.lst
-        fi
-    elif [ -e "${boot_dir}/grub.cfg" -a -e "${TARGET}/etc/default/grub" ] ; then
-        echo "grub2 support is partially supported"
-        echo "please run update-grub after the instance is online"
+        test -z "$KERNEL_ARGS" || \
+            sed --follow-symlinks -i -e 's/\(.*kernel.*\)/\1 '"$KERNEL_ARGS"'/g' "${boot_dir}/menu.lst"
+    elif test -e "${boot_dir}/grub.cfg" && test -e "${TARGET}/etc/default/grub"; then
+        printf 'grub2 support is partially supported\n'
+        printf 'please run update-grub after the instance is online\n'
 
         grub_setup="$(
-            chroot ${TARGET} /bin/sh -c 'which grub-setup || which grub-bios-setup || which grub2-bios-setup'
+            chroot "$TARGET" /bin/sh -c 'which grub-setup || which grub-bios-setup || which grub2-bios-setup'
         )" 2>/dev/null
         # check to see if grub is using UUID's and replace if so
-        if [ -n "$(grep 'root=UUID' ${boot_dir}/grub.cfg)" ] ; then
-            root_uuid="$($VOL_ID $ROOT_DEV)"
-            sed --follow-symlinks -ie "s/\(root=UUID=\)\([a-z0-9-]*\)/\1${root_uuid}/g" \
-                ${boot_dir}/grub.cfg
+        if test -n "$(grep 'root=UUID' "${boot_dir}/grub.cfg")"; then
+            root_uuid="$(eval "$VOL_ID \"$ROOT_DEV\"")"
+            sed --follow-symlinks -i -e 's/\(root=UUID=\)\([a-z0-9-]*\)/\1'"$root_uuid"'/g' \
+                "${boot_dir}/grub.cfg"
         fi
         # additional kernel arguments for the instance
-        if [ -n "${KERNEL_ARGS}" ] ; then
-            sed -ie "s/.*GRUB_CMDLINE_LINUX=\"\(.*\)\"/GRUB_CMDLINE_LINUX=\"\1 ${KERNEL_ARGS}\"/" \
-                ${TARGET}/etc/default/grub
-        fi
+        test -z "$KERNEL_ARGS" || \
+            sed --follow-symlinks -i -e 's/.*GRUB_CMDLINE_LINUX="\(.*\)"/GRUB_CMDLINE_LINUX="\1 '"$KERNEL_ARGS"'/' \
+                "${TARGET}/etc/default/grub"
         # show the menu countdown in case we want to boot to a different kernel
-        sed -ie 's/.*GRUB_HIDDEN_TIMEOUT=.*/GRUB_HIDDEN_TIMEOUT=5/' ${TARGET}/etc/default/grub
-        sed -ie 's/.*GRUB_HIDDEN_TIMEOUT_QUIET=.*/GRUB_HIDDEN_TIMEOUT_QUIET=false/' ${TARGET}/etc/default/grub
+        sed --follow-symlinks -i -e 's/.*GRUB_HIDDEN_TIMEOUT=.*/GRUB_HIDDEN_TIMEOUT=5/' "${TARGET}/etc/default/grub"
+        sed --follow-symlinks -i -e 's/.*GRUB_HIDDEN_TIMEOUT_QUIET=.*/GRUB_HIDDEN_TIMEOUT_QUIET=false/' "${TARGET}/etc/default/grub"
         # install grub2 MBR
-        chroot ${TARGET} ${grub_setup} --force --device-map=${boot_dir_internal}/device.map \
-            --directory=${boot_dir_internal} --root-device="(hd0,1)" "(hd0)" > /dev/null
+        chroot "$TARGET" "$grub_setup" --force --device-map="${boot_dir_internal}/device.map" \
+            --directory="$boot_dir_internal" --root-device='(hd0,1)' '(hd0)' >/dev/null
     fi
 fi
 
 # setup serial console
-if [ "${INSTANCE_HV_serial_console}" = "True" ] ; then
-    if [ ! -e ${TARGET}/dev/${disk} ] ; then
-        setup_disk_devs
-    fi
-    if [ -e "${boot_dir}/menu.lst" ] ; then
+if test 'True' = "$INSTANCE_HV_serial_console"; then
+    test -e "${TARGET}/dev/$disk" || setup_disk_devs
+    if test -e "${boot_dir}/menu.lst"; then
         # grub 0.x
-        sed --follow-symlinks -ie 's/^default.*/default 0\n\nserial --unit=0\nterminal --timeout=3 console serial/' \
-            ${boot_dir}/menu.lst
-        sed --follow-symlinks -ie 's/\(.*kernel.*\)/\1 console=ttyS0,115200n8/g' \
-            ${boot_dir}/menu.lst
-    elif [ -e "${boot_dir}/grub.cfg" -a -e "${TARGET}/etc/default/grub" ] ; then
+        sed --follow-symlinks -i -e 's/^default.*/default 0\n\nserial --unit=0\nterminal --timeout=3 console serial/' \
+            "${boot_dir}/menu.lst"
+        sed --follow-symlinks -i -e 's/\(.*kernel.*\)/\1 console=ttyS0,115200n8/g' \
+            "${boot_dir}/menu.lst"
+    elif test -e "${boot_dir}/grub.cfg" && test -e "${TARGET}/etc/default/grub"; then
         # grub 2.x
         add_devicemap
-        sed -ie 's/.*GRUB_TERMINAL.*/GRUB_TERMINAL=serial/' ${TARGET}/etc/default/grub
-        sed -ie 's/.*GRUB_CMDLINE_LINUX=\"\(.*\)\"/GRUB_CMDLINE_LINUX=\"\1 console=ttyS0,115200n8\"/' \
-            ${TARGET}/etc/default/grub
-        echo "GRUB_SERIAL_COMMAND=\"serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1\"" \
-            >> ${TARGET}/etc/default/grub
+        sed --follow-symlinks -i -e 's/.*GRUB_TERMINAL.*/GRUB_TERMINAL=serial/' "${TARGET}/etc/default/grub"
+        sed --follow-symlinks -i -e 's/.*GRUB_CMDLINE_LINUX="\(.*\)"/GRUB_CMDLINE_LINUX="\1 console=ttyS0,115200n8"/' \
+            "${TARGET}/etc/default/grub"
+        printf 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"\n' \
+            >>"${TARGET}/etc/default/grub"
     else
-        echo "No grub bootloader found, skipping..."
+        log_error 'No grub bootloader found, skipping...'
     fi
 fi
 
 # execute cleanups
 cleanup
 trap - EXIT
-
-exit 0
diff --git a/example/hooks/interfaces b/example/hooks/interfaces
--- a/example/hooks/interfaces
+++ b/example/hooks/interfaces
@@ -24,42 +24,33 @@ set -e
 . ./common.sh
 debug set -x
 
-FQDN="${INSTANCE_NAME}"
-SHORT_NAME="$(echo ${INSTANCE_NAME} | cut -d . -f 1)"
-STATIC=""
+FQDN="$INSTANCE_NAME"
+SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
+STATIC=''
 
-if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
-    log_error "Missing target directory"
-    exit 1
-fi
+test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
 
-if [ -z "${NIC_COUNT}" ] ; then
-    log_error "Missing NIC_COUNT"
-    exit 1
-fi
+test -n "$NIC_COUNT" || { log_error 'Missing NIC_COUNT'; exit 1; }
 
-if [ -f "${NETWORKS_DIR}/instances/${FQDN}" ] ; then
-    STATIC="yes"
-    source ${NETWORKS_DIR}/instances/${FQDN}
-    if [ -f "${NETWORKS_DIR}/subnets/${SUBNET}" ] ; then
-        source ${NETWORKS_DIR}/subnets/${SUBNET}
-    else
-        echo "No subnet file for subnet ${SUBNET}!"
-        exit 1
-    fi
+if test -f "${NETWORKS_DIR}/instances/$FQDN'; then
+    STATIC='yes'
+    . "${NETWORKS_DIR}/instances/$FQDN"
+    test -f "${NETWORKS_DIR}/subnets/$SUBNET" || { log_error "No subnet file for subnet ${SUBNET}!"; exit 1; }
+    . "${NETWORKS_DIR}/subnets/$SUBNET"
 fi
 
 resolvconf() {
-    nl=$'\n'
-    if [ -n "${DNS_SERVERS}" ] && [ -n "${DNS_SEARCH}" ] && [ -n "${DNS_DOMAIN}" ]; then
-        for server in $DNS_SERVERS ; do
-            nameservers="nameserver ${server}${nl}${nameservers}"
+    _nl='
+'
+    if test -n "$DNS_SERVERS" && test -n "$DNS_SEARCH" && test -n "$DNS_DOMAIN"; then
+        for _server in $DNS_SERVERS; do
+            nameservers="nameserver ${_server}${_nl}$nameservers"
         done
 
-        cat > ${TARGET}/etc/resolv.conf << EOF
-${nameservers}
-domain ${DNS_DOMAIN}
-search ${DNS_SEARCH}
+        cat >"${TARGET}/etc/resolv.conf" <<EOF
+$nameservers
+domain $DNS_DOMAIN
+search $DNS_SEARCH
 EOF
     fi
 }
@@ -67,33 +58,30 @@ EOF
 # Functions
 
 systemd_setup() {
-    host_name="$1"
+    _host_name="$1"
     # Update systemd's view of hostname
-    echo "${host_name}" >${TARGET}/etc/hostname
+    printf '%s' "$_host_name" >"${TARGET}/etc/hostname"
     # Clear previous machine-id
-    echo -n >${TARGET}/etc/machine-id
+    cat /dev/null >"${TARGET}/etc/machine-id"
     # Bind mount /dev to get temporary use of /dev/urandom
-    mount --bind /dev ${TARGET}/dev
-    CLEANUP+=("umount ${TARGET}/dev")
+    mount --bind '/dev' "${TARGET}/dev"
+    CLEANUP+=("umount \"${TARGET}/dev\"")
     # Set new machine-id (this works because it writes direct to file)
-    chroot ${TARGET} systemd-machine-id-setup >/dev/null 2>&1
-    umount ${TARGET}/dev
+    chroot "$TARGET" 'systemd-machine-id-setup' >/dev/null 2>&1
+    umount "${TARGET}/dev"
     pop_cleanup
     # Update machine-info
-    cat <<EOF >${TARGET}/etc/machine-info
-PRETTY_HOSTNAME="${host_name}"
+    cat <<EOF >"${TARGET}/etc/machine-info"
+PRETTY_HOSTNAME="$_host_name"
 CHASSIS="vm"
 EOF
 }
 
 debian_setup() {
-    if [ ! -d "${TARGET}/etc/network" ] ; then
-        log_error "Missing target network directory"
-        exit 1
-    fi
+    test -d "${TARGET}/etc/network" || { log_error 'Missing target network directory'; exit 1; }
 
-    if [ -z "${STATIC}" ] ; then
-        cat > ${TARGET}/etc/network/interfaces << EOF
+    if test -z "$STATIC"; then
+        cat >"${TARGET}/etc/network/interfaces" <<EOF
 # This file describes the network interfaces available on your system
 # and how to activate them. For more information, see interfaces(5).
 
@@ -105,7 +93,7 @@ iface eth0 inet dhcp
 
 EOF
     else
-        cat > ${TARGET}/etc/network/interfaces << EOF
+        cat >"${TARGET}/etc/network/interfaces" <<EOF
 # This file describes the network interfaces available on your system
 # and how to activate them. For more information, see interfaces(5).
 
@@ -114,63 +102,58 @@ iface lo inet loopback
 
 auto eth0
 iface eth0 inet static
-    address ${ADDRESS}
-    netmask ${NETMASK}
-    gateway ${GATEWAY}
+    address $ADDRESS
+    netmask $NETMASK
+    gateway $GATEWAY
 EOF
-        if [ -n "${DNS_SERVERS}" ] && [ -n "${DNS_SEARCH}" ] && [ -n "${DNS_DOMAIN}" ]; then
-            cat >> ${TARGET}/etc/network/interfaces << EOF
-    dns-nameservers ${DNS_SERVERS}
-    dns-domain ${DNS_DOMAIN}
-    dns-search ${DNS_SEARCH}
+        if test -n "$DNS_SERVERS" && test -n "$DNS_SEARCH" && test -n "$DNS_DOMAIN"; then
+            cat >>"${TARGET}/etc/network/interfaces" << EOF
+    dns-nameservers $DNS_SERVERS
+    dns-domain $DNS_DOMAIN
+    dns-search $DNS_SEARCH
 
 EOF
         fi
     fi
 
-    if [ -n "${FQDN}" ] ; then
-        if [ -d ${TARGET}/etc/systemd ]; then
-            systemd_setup "${SHORT_NAME}"
+    if test -n "$FQDN"; then
+        if test -d "${TARGET}/etc/systemd"; then
+            systemd_setup "$SHORT_NAME"
         else
-            echo "${SHORT_NAME}" > ${TARGET}/etc/hostname
+            printf '%s\n' "$SHORT_NAME" >"${TARGET}/etc/hostname"
         fi
     fi
 }
 
 redhat_setup() {
-    if [ ! -d "${TARGET}/etc/sysconfig/network-scripts" ] ; then
-        log_error "Missing target network directory"
-        exit 1
-    fi
-    if [ -z "${STATIC}" ] ; then
-        cat > ${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0 << EOF
+    test -d "${TARGET}/etc/sysconfig/network-scripts" || { log_error 'Missing target network directory'; exit 1; }
+    if test -z "$STATIC"; then
+        cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
 DEVICE=eth0
 BOOTPROTO=dhcp
 ONBOOT=yes
 EOF
     else
-        cat > ${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0 << EOF
+        cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
 DEVICE=eth0
 BOOTPROTO=static
-IPADDR=${ADDRESS}
-NETMASK=${NETMASK}
+IPADDR=$ADDRESS
+NETMASK=$NETMASK
 ONBOOT=yes
 EOF
     fi
 
-    if [ -n "${FQDN}" ] ; then
-        cat > ${TARGET}/etc/sysconfig/network << EOF
+    if test -n "$FQDN"; then
+        cat >"${TARGET}/etc/sysconfig/network" << EOF
 NETWORKING=yes
-HOSTNAME=${FQDN}
-GATEWAY=${GATEWAY}
+HOSTNAME=$FQDN
+GATEWAY=$GATEWAY
 EOF
-        if [ -d ${TARGET}/etc/systemd ]; then
-            systemd_setup "${FQDN}"
-        fi
+        ! test -d "${TARGET}/etc/systemd" || systemd_setup "$FQDN"
     else
-        cat > ${TARGET}/etc/sysconfig/network << EOF
+        cat >"${TARGET}/etc/sysconfig/network" <<EOF
 NETWORKING=yes
-GATEWAY=${GATEWAY}
+GATEWAY=$GATEWAY
 EOF
     fi
 
@@ -178,55 +161,49 @@ EOF
 }
 
 gentoo_setup() {
-    if [ ! -f "${TARGET}/etc/conf.d/net" ] ; then
-        log_error "Missing target network file"
-        exit 1
-    fi
-    if [ -z "${STATIC}" ] ; then
-        cat > ${TARGET}/etc/conf.d/net << EOF
-config_eth0=( "dhcp" )
+    test -f "${TARGET}/etc/conf.d/net" || { log_error 'Missing target network file'; exit 1; }
+    if test -z "$STATIC"; then
+        cat >"${TARGET}/etc/conf.d/net" <<EOF
+config_eth0=( 'dhcp' )
 EOF
     else
-        cat > ${TARGET}/etc/conf.d/net << EOF
-config_eth0=( "${ADDRESS} netmask ${NETMASK}" )
-routes_eth0=( "default gw ${GATEWAY}" )
+        cat >"${TARGET}/etc/conf.d/net" <<EOF
+config_eth0=( "$ADDRESS netmask $NETMASK" )
+routes_eth0=( "default gw $GATEWAY" )
 EOF
     fi
 
     resolvconf
 
-    chroot ${TARGET} ln -sf /etc/init.d/net.lo /etc/init.d/net.eth0
-    chroot ${TARGET} rc-update add net.eth0 default
+    chroot "$TARGET" ln -sf /etc/init.d/net.lo /etc/init.d/net.eth0
+    chroot "$TARGET" rc-update add net.eth0 default
 
-    if [ -n "${FQDN}" ] ; then
+    if test -n "$FQDN"; then
         # baselayout-2.x
-        if [ -d "${TARGET}/usr/share/openrc/" ] ; then
-            cat > ${TARGET}/etc/conf.d/hostname << EOF
-hostname="${SHORT_NAME}"
+        if test -d "${TARGET}/usr/share/openrc/"; then
+            cat >"${TARGET}/etc/conf.d/hostname" <<EOF
+hostname="$SHORT_NAME"
 EOF
         else
-            cat > ${TARGET}/etc/conf.d/hostname << EOF
-HOSTNAME="${SHORT_NAME}"
+            cat >"${TARGET}/etc/conf.d/hostname" <<EOF
+HOSTNAME="$SHORT_NAME"
 EOF
         fi
     fi
 }
 
 suse_setup() {
-    if [ ! -d ${TARGET}/etc/sysconfig/network ] ; then
-        log_error "Missing target network directory"
-        exit 1
-    fi
-    cat > ${TARGET}/etc/sysconfig/network/ifcfg-eth0 << EOF
+    test -d "${TARGET}/etc/sysconfig/network" || { log_error 'Missing target network directory'; exit 1; }
+    cat >"${TARGET}/etc/sysconfig/network/ifcfg-eth0" <<EOF
 BOOTPROTO='dhcp4'
 STARTMODE='auto'
 NAME='Ethernet Card 0'
 EOF
-    if [ -n "${FQDN}" ] ; then
-        if [ -d ${TARGET}/etc/systemd ]; then
-            systemd_setup "${FQDN}"
+    if test -n "$FQDN"; then
+        if test -d "${TARGET}/etc/systemd"; then
+            systemd_setup "$FQDN"
         else
-            echo "${FQDN}" > ${TARGET}/etc/HOSTNAME
+            printf '%s' "$FQDN" >"${TARGET}/etc/HOSTNAME"
         fi
     fi
 
@@ -234,14 +211,13 @@ EOF
 }
 
 # Main
-get_os_type $TARGET
+get_os_type
 
-if [ "${NIC_COUNT}" -gt 0 -a -n "${OS_TYPE}" ] ; then
+if test "$NIC_COUNT" -gt 0 && test -n "$OS_TYPE"; then
     ${OS_TYPE}_setup
 else
-    log_error "Unsupported OS_TYPE"
+    log_error 'Unsupported OS_TYPE'
 fi
 
 cleanup
 trap - EXIT
-exit 0
diff --git a/example/hooks/overlays b/example/hooks/overlays
--- a/example/hooks/overlays
+++ b/example/hooks/overlays
@@ -24,18 +24,11 @@ set -e
 . ./common.sh
 debug set -x
 
-if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
-    log_error "Missing target directory"
-    exit 1
-fi
+test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
 
-if [ -n "${OVERLAY}" ] ; then
-    overlay="${OVERLAYS_DIR}/${OVERLAY}"
-    if [ ! -d "${overlay}" ] ; then
-        log_error "${overlay} not found"
-    fi
+if test -n "$OVERLAY"; then
+    overlay="${OVERLAYS_DIR}/$OVERLAY"
+    test -d "$overlay" || { log_error "$overlay not found"; exit 1; }
     # copy overlay files into target instance
-    cp -a ${overlay}/* ${TARGET}
+    cp -ax "$overlay"/* "$TARGET"
 fi
-
-exit 0
diff --git a/example/hooks/zz_ddns b/example/hooks/zz_ddns
--- a/example/hooks/zz_ddns
+++ b/example/hooks/zz_ddns
@@ -24,74 +24,53 @@ set -e
 . ./common.sh
 debug set -x
 
-FQDN="${INSTANCE_NAME}"
-SHORT_NAME="$(echo ${INSTANCE_NAME} | cut -d . -f 1)"
-RENAME=
+FQDN="$INSTANCE_NAME"
+SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
+RENAME=''
 
-if [ -z "${TARGET}" -o ! -d "${TARGET}" ] ; then
-    log_error "Missing target directory"
-    exit 1
-fi
+test -d "$TARGET" || { log_error 'Missing target directory'; exit 1; }
 
-while getopts "r" opt ; do
-    case $opt in
-        r)
-            RENAME=true
-            ;;
-        *)
-            ;;
-    esac
+while getopts 'r' _opt; do
+    ! test 'r' = "$_opt" || RENAME='true'
 done
 
 # Functions
 debian_setup() {
-    local dhclient_conf=""
-    if [ -f "${TARGET}/etc/dhcp/dhclient.conf" ] ; then
-        dhclient_conf="${TARGET}/etc/dhcp/dhclient.conf"
-    elif [ -f "${TARGET}/etc/dhcp3/dhclient.conf" ] ; then
-        dhclient_conf="${TARGET}/etc/dhcp3/dhclient.conf"
+    _dhclient_conf=''
+    if test -f "${TARGET}/etc/dhcp/dhclient.conf"; then
+        _dhclient_conf="${TARGET}/etc/dhcp/dhclient.conf"
+    elif test -f "${TARGET}/etc/dhcp3/dhclient.conf"; then
+        _dhclient_conf="${TARGET}/etc/dhcp3/dhclient.conf"
     else
-        log_error "Missing dhclient.conf file"
+        log_error 'Missing dhclient.conf file'
         exit 1
     fi
 
-    if [ -n "${FQDN}" ] && [ -z "${RENAME}" ] ; then
-        echo "send host-name ${SHORT_NAME};" >> ${dhclient_conf}
+    if test -n "$FQDN" && test -z "$RENAME"; then
+        printf 'send host-name %s;' "$SHORT_NAME" >>"$_dhclient_conf"
     else
-        sed -i -e "s/send host-name.*/send host-name ${SHORT_NAME};/" \
-            ${dhclient_conf}
+        sed --follow-symlinks -i -e 's/send host-name.*/send host-name '"$SHORT_NAME"';/' "$_dhclient_conf"
     fi
 }
 
 redhat_setup() {
-    if [ ! -f "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" ] ; then
-        log_error "Missing ifcfg-eth0 file"
-        exit 1
-    fi
-    if [ -n "${FQDN}" ] && [ -z "${RENAME}" ] ; then
-        echo "DHCP_HOSTNAME=${SHORT_NAME}" >> \
-            ${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0
+    test -f "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" || { log_error 'Missing ifcfg-eth0 file'; exit 1; }
+    if test -n "$FQDN" && test -z "$RENAME"; then
+        printf 'DHCP_HOSTNAME=%s' "$SHORT_NAME" >>"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0"
     else
-        sed -i -e "s/DHCP_HOSTNAME=.*/DHCP_HOSTNAME=${SHORT_NAME}/" \
-            ${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0
+        sed --follow-symlinks -i -e 's/DHCP_HOSTNAME=.*/DHCP_HOSTNAME='"$SHORT_NAME"'/' "${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0"
     fi
 }
 
-gentoo_setup() {
-    echo "no action needed for ddns"
-}
+gentoo_setup() { log_error 'no action needed for ddns'; }
 
-suse_setup() {
-    echo "untested for suse"
-}
+suse_setup() { log_error 'untested for suse'; }
 
 # Main
-get_os_type $TARGET
+get_os_type
 
-if [ "${NIC_COUNT}" -gt 0 -a -n "${OS_TYPE}" ] ; then
-    ${OS_TYPE}_setup
+if test $NIC_COUNT -gt 0 && test -n "$OS_TYPE"; then
+    "${OS_TYPE}_setup"
 else
-    log_error "Unsupported OS_TYPE"
+    log_error 'Unsupported OS_TYPE'
 fi
-
-exit 0
diff --git a/example/pre-hooks/resize_root_partition b/example/pre-hooks/resize_root_partition
--- a/example/pre-hooks/resize_root_partition
+++ b/example/pre-hooks/resize_root_partition
@@ -22,100 +22,96 @@ set -e
 . ./common.sh
 debug set -x
 
-if [ "${IMAGE_TYPE}" = 'qemu' ]; then
+if test 'qemu' = "$IMAGE_TYPE"; then
 
     part_table() {
-        local action="$1" # set, get
+        _action="$1" # set, get
         # sfdisk -d seems to always output in 512-byte sectors regardless of -uX
         # (using -uS here anyway in case someone else's sfdisk has a different default)
-        if [ 'set' = "$action" ]; then
-            ${SFDISK} -L -uS ${BLOCKDEV} 2>/dev/null
+        if test 'set' = "$_action"; then
+            "$SFDISK" -L -uS "$BLOCKDEV" 2>/dev/null
         else
-            ${SFDISK} -L -uS -d ${BLOCKDEV} 2>/dev/null
+            "$SFDISK" -L -uS -d "$BLOCKDEV" 2>/dev/null
         fi
     }
 
     get_part_sizes() {
-        local part_num="$1"
+        _part_num="$1"
         part_table get | \
             sed -n -e '1,/^$/ b; p' | \
             sed -e "$(
-                test -z "$root_part_num" || printf '%d q; ' `expr $part_num + 1`
+                test -z "$root_part_num" || printf '%d q; ' `expr $_part_num + 1`
             )"'s/^.*size= *\([0-9]\+\),.*$/\1/' | \
             tr '\n' ' '
     }
 
     part_size() {
-        local action="$1" # reset, set, get
-        local part_num="$2"
-        if [ 'set' = "$action" ]; then
-            local value="$3"
-        else
-            local value=
-        fi
+        _action="$1" # reset, set, get
+        _part_num="$2"
+        _value=''
+        ! test 'set' = "$_action" || _value="$3"
         part_table get | \
             sed -n -e '1,/^$/ b; p' | \
-            if [ 'get' = "$action" ]; then
-                sed -n -e "${part_num}"'! b; s/^.*size= *\([0-9]\+\),.*$/\1/; p; q'
+            if test 'get' = "$_action"; then
+                sed -n -e "$_part_num"'! b; s/^.*size= *\([0-9]\+\),.*$/\1/; p; q'
             else
-                sed -e "${part_num}"'! b; s/size= *[0-9]\+,/size=,'"${value}/" | \
+                sed -e "$_part_num"'! b; s/size= *[0-9]\+,/size=,'"$_value"'/' | \
                     part_table set
             fi
     }
 
     # Set disk based on type of hypervisor
-    disk=""
-    if [ "${HYPERVISOR}" = "kvm" ] ; then
-        disk="vda"
+    if test 'kvm' = "$HYPERVISOR"; then
+        disk='vda'
     else
-        disk="xda"
+        disk='xda'
     fi
 
     # Get destination disk size in 512-byte sectors
-    device_size=`${BLOCKDEV_CMD} --getsz ${BLOCKDEV}`
+    device_size="`"$BLOCKDEV_CMD" --getsz "$BLOCKDEV"`"
 
     # Get list of assigned partition sizes in table
     part_sizes="`get_part_sizes`"
 
     # Calculate total size used by partitions
     used_size=0
-    for part_size in ${part_sizes}; do
-        used_size=`expr ${used_size} + ${part_size}`
+    for _part_size in $part_sizes; do
+        used_size="`expr $used_size + $_part_size`"
     done
 
     # Abort if device too small
-    if [ ${device_size} -lt ${used_size} ]; then
-        printf 'Device size (%d sectors) is less than size used by partitions (%d sectors). Aborting.\n' "${device_size}" "${used_size}" >&2
+    if test $device_size -lt $used_size; then
+        printf 'Device size (%d sectors) is less than size used by partitions (%d sectors). Aborting.\n' "$device_size" "$used_size" >&2
         cleanup
         trap - EXIT
         exit 1
     fi
 
     # If device too big
-    if [ ${device_size} -gt ${used_size} ]; then
+    if test $device_size -gt $used_size; then
 
         # Get root (final) partition number
-        if [ "${SWAP}" = "yes" ] && [ -z "${KERNEL_PATH}" ] ; then
+        if test 'yes' = "$SWAP" && test -z "$KERNEL_PATH"; then
             part_num=3
-        elif [ "${SWAP}" = "no" ] && [ -z "${KERNEL_PATH}" ] || [ "${SWAP}" = "yes" ] && [ -n "${KERNEL_PATH}" ] ; then
+        elif test 'no' = "$SWAP" && test -z "$KERNEL_PATH" || test 'yes' = "$SWAP" && test -n "$KERNEL_PATH"; then
             part_num=2
-        elif [ "${SWAP}" = "no" ] && [ -n "${KERNEL_PATH}" ] ; then
+        elif test 'no' = "$SWAP" && test -n "$KERNEL_PATH"; then
             part_num=1
         fi
 
         # Expand (maximise) final partition
         part_size reset $part_num
 
-        filesystem_dev=$(map_disk0 ${BLOCKDEV})
-        CLEANUP+=("unmap_disk0 ${BLOCKDEV}")
-        ROOT_DEV=$(map_partition $filesystem_dev root)
+        filesystem_dev="$(map_disk0)"
+        CLEANUP+=('unmap_disk0')
+        ROOT_DEV="$(map_partition "$filesystem_dev" 'root')"
 
         # Expand filesystem on final partition
         #TODO: equivalent commandlines for btrfs, xfs, zfs, ntfs, etc...
-        case `${BLKID} -p -u filesystem -s TYPE -o value ${ROOT_DEV}` in
+        case "`"$BLKID" -p -u filesystem -s TYPE -o value "$ROOT_DEV"`" in
             ext2|ext3|ext4)
-                resize2fs -f ${ROOT_DEV} >/dev/null 2>&1
-                e2fsck -f -n ${ROOT_DEV} >/dev/null 2>&1
+                resize2fs -f "$ROOT_DEV" >/dev/null 2>&1
+                e2fsck -f -n "$ROOT_DEV" >/dev/null 2>&1
                 ;;
         esac
 
@@ -124,4 +120,3 @@ fi
 
 cleanup
 trap - EXIT
-exit 0
diff --git a/export b/export
--- a/export
+++ b/export
@@ -23,58 +23,54 @@ debug set -x
 
 # If the target device is not a real block device we'll first losetup it.
 # This is needed for file disks.
-if [ ! -b $blockdev ]; then
-    ORIGINAL_BLOCKDEV=$blockdev
-    blockdev=$($LOSETUP -sf $blockdev)
-    CLEANUP+=("$LOSETUP -d $blockdev")
+if ! test -b "$BLOCKDEV"; then
+    OLD_BLOCKDEV="$BLOCKDEV"
+    BLOCKDEV="$("$LOSETUP" -sf "$BLOCKDEV")"
+    CLEANUP+=("\"$LOSETUP\" -d \"$BLOCKDEV\"")
 fi
 
-if [ ! "${NOMOUNT}" = "yes" ] ; then
-    filesystem_dev=$(map_disk0 $blockdev)
-    CLEANUP+=("unmap_disk0 $blockdev")
-    root_dev=$(map_partition $filesystem_dev root)
-    boot_dev=$(map_partition $filesystem_dev boot)
+if ! test 'yes' = "$NOMOUNT"; then
+    filesystem_dev="$(map_disk0)"
+    CLEANUP+=('unmap_disk0')
+    root_dev="$(map_partition "$filesystem_dev" root)"
+    boot_dev="$(map_partition "$filesystem_dev" boot)"
 fi
 
-TARGET=`mktemp -d --tmpdir=${EXPORT_DIR}` || exit 1
-CLEANUP+=("rmdir $TARGET")
+TARGET="`mktemp -d --tmpdir="${EXPORT_DIR:-${TMPDIR:-/tmp}}"`"
+CLEANUP+=("rmdir \"$TARGET\"")
 
-if [ "${NOMOUNT}" = "yes" ] ; then
+if test 'yes' = "$NOMOUNT"; then
     # convert block device to qcow2 image to support OS's like Windows. Use
     # qcow2 to conserve on space.
-    $QEMU_IMG convert $blockdev -O qcow2 ${TARGET}/disk.img
-    CLEANUP+=("rm ${TARGET}/disk.img")
+    "$QEMU_IMG" convert "$BLOCKDEV" -O qcow2 "${TARGET}/disk.img"
+    CLEANUP+=("rm -f \"${TARGET}/disk.img\"")
 else
-    vol_type_root="$($VOL_TYPE $root_dev)"
-    if [ -n "${boot_dev}" ] ; then
-        vol_type_boot="$($VOL_TYPE $boot_dev)"
-    fi
+    vol_type_root="$(eval "$VOL_TYPE \"$root_dev\"")"
+    test -z "$boot_dev" || vol_type_boot="$(eval "$VOL_TYPE \"$boot_dev\"")"
 
-    for fs in boot root ; do
-        # use indirect reference to make the variables dynamic
-        dev="$(eval "echo \${$(echo ${fs}_dev)"})"
-        vol_type="$(eval echo \$vol_type_${fs})"
-        if [ -z "$vol_type" -a -n "${dev}" ] ; then
-            log_error "Unable to find ${fs} filesystem type at ${dev}"
-            exit 1
-        fi
-        if [ -n "${dev}" ] ; then
-            if [ "$vol_type" = "ext3" -o "$vol_type" = "ext2" \
-                    -o "$vol_type" = "ext4" ] ; then
-                $DUMP -0 -q -z9 -f ${TARGET}/${fs}.dump $dev
-                CLEANUP+=("rm ${TARGET}/${fs}.dump")
-            else
-                log_error "${fs} is not a supported filesystem. Please use ext{2,3,4}"
-                exit 1
-            fi
+    for _fs in 'boot' 'root'; do
+        # use indirect reference to make the variables dynamic (these are a mess, fix in an
+        # upcoming commit)
+        dev="$(eval "echo \${$(echo ${_fs}_dev)"})"
+        vol_type="$(eval echo \$vol_type_${_fs})"
+        test -n "$vol_type" || test -z "$dev" || { log_error "Unable to find $_fs filesystem type at $dev"; exit 1; }
+        if test -n "$dev"; then
+            case "$vol_type" in
+                ext3|ext2|ext4)
+                    "$DUMP" -0 -q -z9 -f "${TARGET}/${_fs}.dump" "$dev"
+                    CLEANUP+=("rm -f \"${TARGET}/${_fs}.dump\"")
+                    ;;
+                *)
+                    log_error "$_fs is not a supported filesystem. Please use ext{2,3,4}"
+                    exit 1
+                    ;;
+            esac
         fi
     done
 fi
 
-( cd $TARGET ; tar -cf - . )
+( cd "$TARGET"; tar -cf - . )
 
 # execute cleanups
 cleanup
 trap - EXIT
-
-exit 0
diff --git a/tools/ganeti-image.in b/tools/ganeti-image.in
--- a/tools/ganeti-image.in
+++ b/tools/ganeti-image.in
@@ -19,31 +19,33 @@
 
 set -e
 
-[ $GANETI_DEBUG ] && set -x
+test -z "$GANETI_DEBUG" || set -x
 IMAGE_DIR=
 INSTANCE_NAME=
 IMAGE_NAME=
 ARCH=
-HOSTNAME="$(hostname)"
+HOSTNAME="`hostname`"
 
 run_help() {
-    echo "Usage: $0 [-d PATH] [-n NAME] [-a ARCH] -t TYPE -i INSTANCE"
-    echo
-    echo "Create an image of a ganeti instance using either a tarball, dump, or qemu image.."
-    echo
-    echo "-t TYPE       Type of image, either: tarball, dump, or qemu-img"
-    echo "-d PATH       Path of where to put the image"
-    echo "-i INSTANCE   Name of the instance"
-    echo "-n NAME       Name of the image"
-    echo "-a ARCH       Architecture of the image"
-    echo
-    echo "This utility must be used on the master node. All optional args will"
-    echo "have defaults if you do not set them."
+    cat <<EOF
+Usage: $0 [-d PATH] [-n NAME] [-a ARCH] -t TYPE -i INSTANCE
+
+Create an image of a ganeti instance using either a tarball, dump, or qemu image..
+
+-t TYPE       Type of image, either: tarball, dump, or qemu-img
+-d PATH       Path of where to put the image
+-i INSTANCE   Name of the instance
+-n NAME       Name of the image
+-a ARCH       Architecture of the image
+
+This utility must be used on the master node. All optional args will
+have defaults if you do not set them.
+EOF
     exit 0
 }
 
-while getopts "hd:i:a:n:t:" opt ; do
-    case $opt in
+while getopts "hd:i:a:n:t:" _opt ; do
+    case "$_opt" in
         t)
             TYPE="$OPTARG"
             ;;
@@ -67,51 +69,51 @@ while getopts "hd:i:a:n:t:" opt ; do
     esac
 done
 
-#[ -z "$IMAGE_DIR" ] && echo "Error: Image path not set" && exit 1
-[ -z "$INSTANCE_NAME" ] && echo "Error: Instance name not set" && exit 1
-[ -z "$TYPE" ] && echo "Error: Image type not set" && exit 1
+#test -n "$IMAGE_DIR" || { printf 'Error: Image path not set\n'; exit 1; }
+test -n "$INSTANCE_NAME" || { printf 'Error: Instance name not set\n'; exit 1; }
+test -n "$TYPE" || printf 'Error: Image type not set\n'; exit 1; }
 
-incorrect_type=1
-for i in tarball dump qemu-img ; do
-    if [ "$i" == $TYPE ] ; then
-        incorrect_type=0
-    fi
-done
-
-[ "$incorrect_type" == "1" ] && echo "Error: Incorrect type set" && exit 1
+case "$TYPE" in
+    tarball|dump|qemu)
+        :
+        ;;
+    *)
+        printf 'Error: Incorrect type set\n'
+        exit 1
+        ;;
+esac
 
 # Am I master?
-if [ "$(gnt-cluster getmaster)" != "${HOSTNAME}" ] ; then
-    echo "ERROR: Command must be run from master node"
+if ! test "x`gnt-cluster getmaster`" = "x$HOSTNAME"; then
+    printf 'ERROR: Command must be run from master node\n'
     exit 1
 fi
 
 # Gather some information
-info=($(gnt-instance list -o os,hypervisor,disk.count,hv/kernel_path --no-headers --separator=' ' $INSTANCE_NAME))
+info="$(gnt-instance list -o os,hypervisor,disk.count,hv/kernel_path --no-headers --separator=' ' "$INSTANCE_NAME")"
 OS_VARIANT="${info[0]/*+/}"
 HYPERVISOR="${info[1]}"
 DISK_COUNT="${info[2]}"
 INSTANCE_HV_kernel_path="${info[3]}"
-OS_API_VERSION="20"
+OS_API_VERSION=20
 
 # Activate disks and capture output
-ad_output=($(gnt-instance activate-disks $INSTANCE_NAME | sed -e 's/\:/ /g'))
+ad_output="$(gnt-instance activate-disks "$INSTANCE_NAME" | sed -e 's/\:/ /g')"
 
 # Get node/disk path
 NODE="${ad_output[0]}"
 DISK_0_PATH="${ad_output[2]}"
 
-export OS_VARIANT HYPERVISOR DISK_COUNT OS_API_VERSION DISK_0_PATH \
-    INSTANCE_HV_kernel_path
+export OS_VARIANT HYPERVISOR DISK_COUNT OS_API_VERSION DISK_0_PATH INSTANCE_HV_kernel_path
 
-echo "Creating image with type $TYPE from $INSTANCE_NAME in ${IMAGE_DIR} from node $NODE"
+printf 'Creating image with type %s from %s in %s from node %s\n' "$TYPE" "$INSTANCE_NAME" "$IMAGE_DIR" from node "$NODE"
 
-if [ "$NODE" == "$HOSTNAME" ] ; then
-    @osdir@/@osname@/tools/make-image -i $INSTANCE_NAME \
-        $IMAGE_DIR $IMAGE_NAME $ARCH -t $TYPE
+if test "x$NODE" = "x$HOSTNAME"; then
+    "@osdir@/@osname@/tools/make-image" -i "$INSTANCE_NAME" \
+        "$IMAGE_DIR" "$IMAGE_NAME" "$ARCH" -t "$TYPE"
 else
-    ssh $NODE @osdir@/@osname@/tools/make-image \
-        -i $INSTANCE_NAME $IMAGE_DIR $IMAGE_NAME $ARCH -t $TYPE
+    ssh "$NODE" "@osdir@/@osname@/tools/make-image" \
+        -i "$INSTANCE_NAME" "$IMAGE_DIR" "$IMAGE_NAME" "$ARCH" -t "$TYPE"
 fi
 
-gnt-instance deactivate-disks $INSTANCE_NAME
+gnt-instance deactivate-disks "$INSTANCE_NAME"
diff --git a/tools/make-image.in b/tools/make-image.in
--- a/tools/make-image.in
+++ b/tools/make-image.in
@@ -19,29 +19,31 @@
 
 set -e
 
-[ $GANETI_DEBUG ] && set -x
+test -z "$GANETI_DEBUG" || set -x
 IMAGE_DIR2=
 INSTANCE_NAME=
 IMAGE_NAME2=
 ARCH2=
 
 run_help() {
-    echo "Usage: $0 -n NAME -m IMAGE_DIR -a ARCH -i INSTANCE_NAME -t TYPE"
-    echo
-    echo "Create an image tarball of a ganeti instance."
-    echo
-    echo "-t TYPE           Image type, either: tarball, dump, or qemu-img"
-    echo "-m IMAGE_DIR      Path of where to put the tarball"
-    echo "-i INSTANCE_NAME  Name of the instance"
-    echo "-n IMAGE_NAME     Name of the tarball image"
-    echo "-a ARCH           Architecture of the image"
-    echo
-    echo "This is a helper utility for the ganeti-image script"
+    cat <<EOF
+Usage: $0 -n NAME -m IMAGE_DIR -a ARCH -i INSTANCE_NAME -t TYPE
+
+Create an image tarball of a ganeti instance.
+
+-t TYPE           Image type, either: tarball, dump, or qemu-img
+-m IMAGE_DIR      Path of where to put the tarball
+-i INSTANCE_NAME  Name of the instance
+-n IMAGE_NAME     Name of the tarball image
+-a ARCH           Architecture of the image
+
+This is a helper utility for the ganeti-image script
+EOF
     exit 0
 }
 
-while getopts ":hi:a:n:m:t:" opt ; do
-    case $opt in
+while getopts ':hi:a:n:m:t:' _opt ; do
+    case "$_opt" in
         t)
             TYPE="$OPTARG"
             ;;
@@ -65,69 +67,66 @@ while getopts ":hi:a:n:m:t:" opt ; do
     esac
 done
 
-. @osdir@/@osname@/common.sh
+. "@osdir@/@osname@/common.sh"
 
 # Set overrides
-[ -n "$IMAGE_DIR2" ]        && IMAGE_DIR=$IMAGE_DIR2
-[ -n "$IMAGE_NAME2" ]       && IMAGE_NAME=$IMAGE_NAME2
-[ -n "$ARCH2" ]             && ARCH=$ARCH2
+test -z "$IMAGE_DIR2" || IMAGE_DIR="$IMAGE_DIR2"
+test -z "$IMAGE_NAME2" || IMAGE_NAME="$IMAGE_NAME2"
+test -z "$ARCH2" || ARCH="$ARCH2"
 
 # Sanity checks
-[ -z "$IMAGE_DIR" ]     && echo "Error: IMAGE_DIR not set" && exit 1
-[ -z "$TYPE" ]          && echo "Error: Image type not set" && exit 1
-[ -z "$INSTANCE_NAME" ] && echo "Error: INSTANCE_NAME not set" && exit 1
-[ -z "$INSTANCE_HV_kernel_path" ] && \
-    echo "Error: INSTANCE_HV_kernel_path not set" && exit 1
-[ -z "$IMAGE_NAME" ]    && echo "Error: IMAGE_NAME not set" && exit 1
-[ -z "$ARCH" ]          && echo "Error: ARCH not set" && exit 1
-[ -z "$OS_VARIANT" ]    && echo "Error: OS_VARIANT not set" && exit 1
-[ -z "$HYPERVISOR" ]    && echo "Error: HYPERVISOR not set" && exit 1
-[ -z "$DISK_COUNT" ]    && echo "Error: DISK_COUNT not set" && exit 1
-[ -z "$OS_API_VERSION" ] && echo "Error: OS_API_VERSION not set" && exit 1
-[ -z "$DISK_0_PATH" ]   && echo "Error: DISK_0_PATH not set" && exit 1
-[ ! -d $IMAGE_DIR ]       && echo "Error: $IMAGE_DIR not found" && exit 1
+test -n "$IMAGE_DIR" || { log_error 'Error: IMAGE_DIR not set'; exit 1; }
+test -n "$TYPE" || { log_error 'Error: Image type not set'; exit 1; }
+test -n "$INSTANCE_NAME" || { log_error 'Error: INSTANCE_NAME not set'; exit 1; }
+test -n "$INSTANCE_HV_kernel_path" || { log_error 'Error: INSTANCE_HV_kernel_path not set'; exit 1; }
+test -n "$IMAGE_NAME" || { log_error 'Error: IMAGE_NAME not set'; exit 1; }
+test -n "$ARCH" || { log_error 'Error: ARCH not set'; exit 1; }
+test -n "$OS_VARIANT" || { log_error 'Error: OS_VARIANT not set'; exit 1; }
+test -n "$HYPERVISOR" || { log_error 'Error: HYPERVISOR not set'; exit 1; }
+test -n "$DISK_COUNT" || { log_error 'Error: DISK_COUNT not set'; exit 1; }
+test -n "$OS_API_VERSION" || { log_error 'Error: OS_API_VERSION not set'; exit 1; }
+test -n "$DISK_0_PATH" || { log_error 'Error: DISK_0_PATH not set'; exit 1; }
+test -d "$IMAGE_DIR" || { log_error "Error: $IMAGE_DIR not found"; exit 1; }
 
 # Setup partitions w/ kpartx
-filesystem_dev=$(map_disk0 $blockdev)
-CLEANUP+=("unmap_disk0 $blockdev")
-root_dev=$(map_partition $filesystem_dev root)
-boot_dev=$(map_partition $filesystem_dev boot)
+filesystem_dev="$(map_disk0)"
+CLEANUP+=('unmap_disk0')
+root_dev="$(map_partition "$filesystem_dev" root)"
+boot_dev="$(map_partition "$filesystem_dev" boot)"
 
-case $TYPE in
+case "$TYPE" in
     tarball)
         # Make temp dir for mounting
-        TARGET=`mktemp -d` || exit 1
-        CLEANUP+=("rmdir $TARGET")
+        TARGET="`mktemp -d`"
+        CLEANUP+=("rmdir \"$TARGET\"")
 
         # Mount filesystems
-        mount_disk0 $TARGET
+        mount_disk0
 
-        OLDPWD=$PWD
-        cd $TARGET
+        OLDPWD="$PWD"
+        cd "$TARGET"
 
-        echo "Creating tarball from $INSTANCE_NAME to ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz"
-        if [ -x /usr/bin/pigz ] ; then
-            tar -I /usr/bin/pigz --numeric-owner -cpf ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz .
+        log_error "Creating tarball from $INSTANCE_NAME to ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz"
+        if test -x '/usr/bin/pigz'; then
+            tar -I '/usr/bin/pigz' --numeric-owner -cpf "${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz" .
         else
-            tar --numeric-owner -zcpf ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz .
+            tar --numeric-owner -zcpf "${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.tar.gz" .
         fi
         ;;
     dump)
-        if [ -n "$boot_dev" ] ; then
-            echo "Creating dump from $INSTANCE_NAME for boot at ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-boot.dump"
-            $DUMP -0 -q -z9 -f ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-boot.dump $boot_dev 2> /dev/null
+        if test -n "$boot_dev"; then
+            log_error "Creating dump from $INSTANCE_NAME for boot at ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-boot.dump"
+            "$DUMP" -0 -q -z9 -f "${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-boot.dump" "$boot_dev" 2> /dev/null
         fi
 
-        echo "Creating dump from $INSTANCE_NAME for root at ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-root.dump"
-        $DUMP -0 -q -z9 -f ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-root.dump $root_dev
+        log_error "Creating dump from $INSTANCE_NAME for root at ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-root.dump"
+        "$DUMP" -0 -q -z9 -f "${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}-root.dump" "$root_dev"
         ;;
     qemu-img)
-        echo "Creating qemu-img image from $INSTANCE_NAME to ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img"
-        $QEMU_IMG convert -O qcow2 $DISK_0_PATH ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img
+        log_error "Creating qemu image from $INSTANCE_NAME to ${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img"
+        "$QEMU_IMG" convert -O qcow2 "$DISK_0_PATH" "${IMAGE_DIR}/${IMAGE_NAME}-${ARCH}.img"
         ;;
     *)
-        echo "Command $TYPE not supported!"
+        log_error "Command $TYPE not supported!"
         ;;
 esac
-
-cd $OLDPWD
