Rewrite interfaces hook
* Improve and standardise systemd handling
* Split systemd functions to separate network/hostname functions
* Reorder functions
* Standardise local/non-local variable/function names

diff --git a/example/hooks/interfaces b/example/hooks/interfaces
--- a/example/hooks/interfaces
+++ b/example/hooks/interfaces
@@ -29,54 +29,78 @@ SHORT_NAME="$(printf '%s' "$INSTANCE_NAME" | cut -d. -f1)"
 STATIC=''
 test -d "$TARGET" || die 'Missing target directory\n'
 test -n "$NIC_COUNT" || die 'Missing NIC_COUNT\n'
-if test -f "${NETWORKS_DIR}/instances/$FQDN'; then
+if test -f "${NETWORKS_DIR}/instances/$FQDN"; then
     STATIC='yes'
     . "${NETWORKS_DIR}/instances/$FQDN"
-    test -f "${NETWORKS_DIR}/subnets/$SUBNET" || die 'No subnet file for subnet %s!\n' "$SUBNET"
+    test -f "${NETWORKS_DIR}/subnets/$SUBNET" || die 'No subnet file for subnet "%s"!\n' "$SUBNET"
     . "${NETWORKS_DIR}/subnets/$SUBNET"
 fi
 
-resolvconf() {
-    _nl='
-'
+_resolvconf() {
     if test -n "$DNS_SERVERS" && test -n "$DNS_SEARCH" && test -n "$DNS_DOMAIN"; then
+        _nameservers=''
         for _server in $DNS_SERVERS; do
-            nameservers="nameserver ${_server}${_nl}$nameservers"
+            _nameservers="nameserver ${_server}
+$_nameservers"
         done
         cat >"${TARGET}/etc/resolv.conf" <<EOF
-$nameservers
+$_nameservers
 domain $DNS_DOMAIN
 search $DNS_SEARCH
 EOF
     fi
 }
 
-# Functions
-
-systemd_setup() {
-    _host_name="$1"
-    # Update systemd's view of hostname
-    printf '%s' "$_host_name" >"${TARGET}/etc/hostname"
-    # Clear previous machine-id
+_systemd_hostname_setup() {
+    printf 'CHASSIS="vm"\n' >"${TARGET}/etc/machine-info"
     cat /dev/null >"${TARGET}/etc/machine-id"
-    # Bind mount /dev to get temporary use of /dev/urandom
-    mount --bind '/dev' "${TARGET}/dev"
+    mount --bind '/dev' "${TARGET}/dev" # to get temporary use of /dev/urandom
     cleanup push "umount \"${TARGET}/dev\""
-    # Set new machine-id (this works because it writes direct to file)
-    chroot "$TARGET" 'systemd-machine-id-setup' >/dev/null 2>&1
+    chroot "$TARGET" 'systemd-machine-id-setup' >/dev/null 2>&1 # works as it writes direct to file
     umount "${TARGET}/dev"
     cleanup pop
-    # Update machine-info
-    cat <<EOF >"${TARGET}/etc/machine-info"
-PRETTY_HOSTNAME="$_host_name"
-CHASSIS="vm"
-EOF
+    printf '%s' "${FQDN:-$SHORT_NAME}" >"${TARGET}/etc/hostname"
+    printf 'PRETTY_HOSTNAME="%s"\n' "${FQDN:-$SHORT_NAME}" >>"${TARGET}/etc/machine-info"
+    printf 'HOSTNAME="%s"\n' "${FQDN:-$SHORT_NAME}" >>"${TARGET}/etc/sysconfig/network"
 }
 
-debian_setup() {
-    test -d "${TARGET}/etc/network" || die 'Missing target network directory\n'
-    if test -z "$STATIC"; then
-        cat >"${TARGET}/etc/network/interfaces" <<EOF
+_systemd_network_setup() {
+    if test 0 -ne $NIC_COUNT; then
+        test -f "${TARGET}/etc/sysconfig/network" || die 'Missing target network file\n'
+        test -d "${TARGET}/etc/sysconfig/network-scripts" || die 'Missing target network-scripts directory\n'
+        if test -z "$FQDN"; then
+            printf 'NETWORKING="no"\n' >"${TARGET}/etc/sysconfig/network"
+        else
+            printf 'NETWORKING="yes"\n' >"${TARGET}/etc/sysconfig/network"
+        fi
+        cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
+NAME='Ethernet Card 0'
+DEVICE='eth0'
+STARTMODE='auto'
+ONBOOT='yes'
+EOF
+        if test -n "$STATIC"; then
+            printf 'BOOTPROTO="static"\n' >>"${TARGET}/etc/sysconfig/network"
+            cat >>"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
+IPADDR='$ADDRESS'
+NETMASK='$NETMASK'
+GATEWAY='$GATEWAY'
+EOF
+        else
+            printf 'BOOTPROTO="dhcp"\n' >>"${TARGET}/etc/sysconfig/network"
+        fi
+    fi
+}
+
+_debian_setup() {
+    if test 'systemd' = "`get_service_manager`"; then
+        _systemd_network_setup
+        _systemd_hostname_setup
+    else
+        test -d "${TARGET}/etc/network" || die 'Missing target network directory\n'
+        if test 0 -ne $NIC_COUNT; then
+            if test -z "$STATIC"; then
+                cat >"${TARGET}/etc/network/interfaces" <<EOF
 # This file describes the network interfaces available on your system
 # and how to activate them. For more information, see interfaces(5).
 
@@ -87,8 +111,8 @@ auto eth0
 iface eth0 inet dhcp
 
 EOF
-    else
-        cat >"${TARGET}/etc/network/interfaces" <<EOF
+            else
+                cat >"${TARGET}/etc/network/interfaces" <<EOF
 # This file describes the network interfaces available on your system
 # and how to activate them. For more information, see interfaces(5).
 
@@ -101,108 +125,46 @@ iface eth0 inet static
     netmask $NETMASK
     gateway $GATEWAY
 EOF
-        if test -n "$DNS_SERVERS" && test -n "$DNS_SEARCH" && test -n "$DNS_DOMAIN"; then
-            cat >>"${TARGET}/etc/network/interfaces" << EOF
-    dns-nameservers $DNS_SERVERS
-    dns-domain $DNS_DOMAIN
-    dns-search $DNS_SEARCH
-
-EOF
+            fi
         fi
+        printf '%s\n' "${FQDN:-$SHORT_NAME}" >"${TARGET}/etc/hostname"
     fi
+}
 
-    if test -n "$FQDN"; then
-        if test -d "${TARGET}/etc/systemd"; then
-            systemd_setup "$SHORT_NAME"
+_gentoo_setup() {
+    if test 0 -ne $NIC_COUNT; then
+        test -f "${TARGET}/etc/conf.d/net" || die 'Missing target network file\n'
+        if test -z "$STATIC"; then
+            cat >"${TARGET}/etc/conf.d/net" <<EOF
+config_eth0=( "dhcp" )
+EOF
         else
-            printf '%s\n' "$SHORT_NAME" >"${TARGET}/etc/hostname"
-        fi
-    fi
-}
-
-redhat_setup() {
-    test -d "${TARGET}/etc/sysconfig/network-scripts" || die 'Missing target network directory\n'
-    if test -z "$STATIC"; then
-        cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
-DEVICE=eth0
-BOOTPROTO=dhcp
-ONBOOT=yes
-EOF
-    else
-        cat >"${TARGET}/etc/sysconfig/network-scripts/ifcfg-eth0" <<EOF
-DEVICE=eth0
-BOOTPROTO=static
-IPADDR=$ADDRESS
-NETMASK=$NETMASK
-ONBOOT=yes
-EOF
-    fi
-    if test -n "$FQDN"; then
-        cat >"${TARGET}/etc/sysconfig/network" << EOF
-NETWORKING=yes
-HOSTNAME=$FQDN
-GATEWAY=$GATEWAY
-EOF
-        ! test -d "${TARGET}/etc/systemd" || systemd_setup "$FQDN"
-    else
-        cat >"${TARGET}/etc/sysconfig/network" <<EOF
-NETWORKING=yes
-GATEWAY=$GATEWAY
-EOF
-    fi
-    resolvconf
-}
-
-gentoo_setup() {
-    test -f "${TARGET}/etc/conf.d/net" || die 'Missing target network file\n'
-    if test -z "$STATIC"; then
-        cat >"${TARGET}/etc/conf.d/net" <<EOF
-config_eth0=( 'dhcp' )
-EOF
-    else
-        cat >"${TARGET}/etc/conf.d/net" <<EOF
+            cat >"${TARGET}/etc/conf.d/net" <<EOF
 config_eth0=( "$ADDRESS netmask $NETMASK" )
 routes_eth0=( "default gw $GATEWAY" )
 EOF
+        fi
+        chroot "$TARGET" ln -sf /etc/init.d/net.lo /etc/init.d/net.eth0
+        chroot "$TARGET" rc-update add net.eth0 default
     fi
-    resolvconf
-    chroot "$TARGET" ln -sf /etc/init.d/net.lo /etc/init.d/net.eth0
-    chroot "$TARGET" rc-update add net.eth0 default
     if test -n "$FQDN"; then
         # baselayout-2.x
         if test -d "${TARGET}/usr/share/openrc/"; then
-            cat >"${TARGET}/etc/conf.d/hostname" <<EOF
-hostname="$SHORT_NAME"
-EOF
+            printf 'hostname="%s"\n' "$SHORT_NAME" >"${TARGET}/etc/conf.d/hostname"
         else
-            cat >"${TARGET}/etc/conf.d/hostname" <<EOF
-HOSTNAME="$SHORT_NAME"
-EOF
+            printf 'HOSTNAME="%s"\n' "$SHORT_NAME" >"${TARGET}/etc/conf.d/hostname"
         fi
     fi
 }
 
-suse_setup() {
-    test -d "${TARGET}/etc/sysconfig/network" || die 'Missing target network directory\n'
-    cat >"${TARGET}/etc/sysconfig/network/ifcfg-eth0" <<EOF
-BOOTPROTO='dhcp4'
-STARTMODE='auto'
-NAME='Ethernet Card 0'
-EOF
-    if test -n "$FQDN"; then
-        if test -d "${TARGET}/etc/systemd"; then
-            systemd_setup "$FQDN"
-        else
-            printf '%s' "$FQDN" >"${TARGET}/etc/HOSTNAME"
-        fi
-    fi
-    resolvconf
-}
+_suse_setup() { _systemd_network_setup; _systemd_hostname_setup; }
 
-# Main
+_redhat_setup() { _systemd_network_setup; _systemd_hostname_setup; }
+
 get_os_type
-if test "$NIC_COUNT" -gt 0 && test -n "$OS_TYPE"; then
-    ${OS_TYPE}_setup
+if test -n "$OS_TYPE"; then
+    "_${OS_TYPE}_setup"
+    _resolvconf
 else
     die 'Unsupported OS_TYPE\n'
 fi
